{
  "hash": "8514f1ff94b68c8f745653a4a7635b0e",
  "result": {
    "markdown": "---\ntitle: \"Tidytuesday 2024-01-23\"\nsubtitle: \"Educational attainment and town size\"\nauthor: \n  - \"Brendan Clarke\"\n  - \"Andrew Saul\"\n  - \"Nick Christofides\"\n  - \"Kennedy Owuso-Afrije\"\n  - \"Jon Minton\"\ndate: \"2024-01-25\"\ncategories: [R, Education, Tidy Tuesday]\n---\n\n\n## Background\n\n[This week's TidyTuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2024/2024-01-23/readme.md) used data from the UK ONS which was explored in the 2023 article ['Why do children and young people in smaller towns do better academically than those in larger towns?](https://www.ons.gov.uk/peoplepopulationandcommunity/educationandchildcare/articles/whydochildrenandyoungpeopleinsmallertownsdobetteracademicallythanthoseinlargertowns/2023-07-25)'. \n\n## Aims\n\nOur first aim was to try to replicate the headline finding from the article above: that children in smaller towns have better average educational outcomes than in larger towns. We also sought to replicate and improve on the 'beeswarm' plot used in the original article, and to look at other factors which may explain differences in educational qualifications.\n\n## Package loading\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggbeeswarm) # for the beeswarm plot\n```\n:::\n\n\n\n## Data\n\n::: {.cell}\n\n```{.r .cell-code}\n# ee <- tidytuesdayR::tt_load('2024-01-23') |>\n#   purrr::pluck(1)\n\n# Direct link to get past API rate limit issue using tt_load()\nee <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-01-23/english_education.csv')\n```\n:::\n\n\n`purrr::pluck(1)` was used because the data contained only a single dataset, but by default the `tt_load` function returns a list. So, the `pluck(1)` function takes the first element of the list, which in this case is in effect turning the data into a dataframe. \n\n## Counting towns in data\n\n::: {.cell}\n\n```{.r .cell-code}\nee |>\n  count(size_flag, sort=T) |>\n  knitr::kable(caption = \"Counts of small/med/city class\")\n```\n\n::: {.cell-output-display}\nTable: Counts of small/med/city class\n\n|size_flag        |   n|\n|:----------------|---:|\n|Small Towns      | 662|\n|Medium Towns     | 331|\n|Large Towns      |  89|\n|City             |  18|\n|Inner London BUA |   1|\n|Not BUA          |   1|\n|Other Small BUAs |   1|\n|Outer london BUA |   1|\n:::\n:::\n\n\nThere are 662 small towns, 331 medium towns, and 89 large towns\n\n## Removing oddball locations and Londons and factoring\n\n::: {.cell}\n\n```{.r .cell-code}\nee |>\n  mutate(town_size = factor(size_flag, levels = c(\"Small Towns\", \"Medium Towns\", \"Large Towns\"), ordered=T)) |>\n  filter(!is.na(town_size)) -> ee_fact\n```\n:::\n\n\n## Summary by group\n\n::: {.cell}\n\n```{.r .cell-code}\nee_fact |>\n  group_by(town_size) |>\n  summarise(count = n(),\n            `mean ed score` = mean(education_score),\n            `sd ed score` = sd(education_score),\n            se = `sd ed score`/count^0.5,\n            `total population` = sum(population_2011)) |>\n  mutate(across(where(is.numeric), round, 3)) |>\n  knitr::kable()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: There was 1 warning in `mutate()`.\nℹ In argument: `across(where(is.numeric), round, 3)`.\nCaused by warning:\n! The `...` argument of `across()` is deprecated as of dplyr 1.1.0.\nSupply arguments directly to `.fns` through an anonymous function instead.\n\n  # Previously\n  across(a:b, mean, na.rm = TRUE)\n\n  # Now\n  across(a:b, \\(x) mean(x, na.rm = TRUE))\n```\n:::\n\n::: {.cell-output-display}\n|town_size    | count| mean ed score| sd ed score|    se| total population|\n|:------------|-----:|-------------:|-----------:|-----:|----------------:|\n|Small Towns  |   662|         0.297|       3.887| 0.151|          6880216|\n|Medium Towns |   331|        -0.253|       3.324| 0.183|         12213733|\n|Large Towns  |    89|        -0.811|       2.298| 0.244|         10466343|\n:::\n:::\n\n\n\n\n## ANOVA for small/med/large towns\n\nWe built a series of linear regression models, and used ANOVA to compare between them. \nA low p-value from ANOVA, when comparing two or more models that are 'nested', can be taken as a signal that the more complex/unrestricted of the models should be used. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_base <- lm(education_score ~ town_size, data = ee_fact)\nsummary(mod_base)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = education_score ~ town_size, data = ee_fact)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.3246  -2.5270  -0.1996   2.3052  11.5749 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)   \n(Intercept) -0.255991   0.151293  -1.692  0.09093 . \ntown_size.L -0.783553   0.288560  -2.715  0.00673 **\ntown_size.Q -0.003547   0.232530  -0.015  0.98783   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.615 on 1079 degrees of freedom\nMultiple R-squared:  0.009593,\tAdjusted R-squared:  0.007758 \nF-statistic: 5.226 on 2 and 1079 DF,  p-value: 0.005513\n```\n:::\n\n```{.r .cell-code}\nmod_dep <- lm(education_score ~ town_size + income_flag, data = ee_fact)\nsummary(mod_dep)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = education_score ~ town_size + income_flag, data = ee_fact)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.4402 -1.8983 -0.0131  1.8447  9.2254 \n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                        -2.29448    0.14533 -15.788  < 2e-16 ***\ntown_size.L                         0.51810    0.22501   2.303   0.0215 *  \ntown_size.Q                        -0.01572    0.17726  -0.089   0.9293    \nincome_flagLower deprivation towns  5.31339    0.19207  27.664  < 2e-16 ***\nincome_flagMid deprivation towns    1.82601    0.23489   7.774 1.77e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.754 on 1077 degrees of freedom\nMultiple R-squared:  0.4261,\tAdjusted R-squared:  0.424 \nF-statistic: 199.9 on 4 and 1077 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nmod_dep2 <- lm(education_score ~ town_size * income_flag, data = ee_fact)\nsummary(mod_dep2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = education_score ~ town_size * income_flag, data = ee_fact)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-9.576 -1.868 -0.049  1.788  9.090 \n\nCoefficients:\n                                               Estimate Std. Error t value\n(Intercept)                                    -2.19244    0.15155 -14.466\ntown_size.L                                     0.94843    0.28240   3.359\ntown_size.Q                                    -0.10774    0.24096  -0.447\nincome_flagLower deprivation towns              4.77144    0.30602  15.592\nincome_flagMid deprivation towns                1.59836    0.31953   5.002\ntown_size.L:income_flagLower deprivation towns -1.36508    0.60094  -2.272\ntown_size.Q:income_flagLower deprivation towns -0.11774    0.44806  -0.263\ntown_size.L:income_flagMid deprivation towns   -0.76520    0.61668  -1.241\ntown_size.Q:income_flagMid deprivation towns   -0.04965    0.48199  -0.103\n                                               Pr(>|t|)    \n(Intercept)                                     < 2e-16 ***\ntown_size.L                                    0.000811 ***\ntown_size.Q                                    0.654869    \nincome_flagLower deprivation towns              < 2e-16 ***\nincome_flagMid deprivation towns               6.62e-07 ***\ntown_size.L:income_flagLower deprivation towns 0.023309 *  \ntown_size.Q:income_flagLower deprivation towns 0.792769    \ntown_size.L:income_flagMid deprivation towns   0.214935    \ntown_size.Q:income_flagMid deprivation towns   0.917974    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.749 on 1073 degrees of freedom\nMultiple R-squared:  0.4305,\tAdjusted R-squared:  0.4262 \nF-statistic: 101.4 on 8 and 1073 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nanova(mod_base, mod_dep, mod_dep2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: education_score ~ town_size\nModel 2: education_score ~ town_size + income_flag\nModel 3: education_score ~ town_size * income_flag\n  Res.Df     RSS Df Sum of Sq        F  Pr(>F)    \n1   1079 14097.2                                  \n2   1077  8168.3  2    5928.9 392.3729 < 2e-16 ***\n3   1073  8106.8  4      61.5   2.0343 0.08749 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nanova(mod_dep, mod_dep2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: education_score ~ town_size + income_flag\nModel 2: education_score ~ town_size * income_flag\n  Res.Df    RSS Df Sum of Sq      F  Pr(>F)  \n1   1077 8168.3                              \n2   1073 8106.8  4    61.479 2.0343 0.08749 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThe summary from `mod_dep` indicates that deprivation tertile, using the IMD income domain, may have more of an effect than town size, and in the opposite direction. \n\n## Beeswarm plot\n\nWe reproduce the beeswarm plot from the original article, but colouring areas by income tertile:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee_fact |>\n  mutate(income_flag = factor(income_flag, levels = c(\"Lower deprivation towns\", \"Mid deprivation towns\", \"Higher deprivation towns\"))) |>\n  ggplot(aes(x = town_size, y = education_score, color = income_flag)) +\n  geom_beeswarm() +\n  coord_flip() +\n  theme(legend.position = \"bottom\") +\n  scale_color_manual(values = c(\"#73b8fd\", \"#0068c6\", \"#003b7c\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n## Conclusion\n\nWe were able to replicate the headline finding from the article, and the type of visualisation used. But we also identified area deprivation as an important (and likely a more important) determinant of education scores. ",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}