---
title: "Threw missiles: a concealed tautology?"
author: "Jon Minton"
date: "2024-08-10"
categories: [linguistics]
---

It's probably amongst the least important thing to reflect on in the context of the reported violence and disorder that's occurred in the last couple of weeks, but in reports on the BBC (for example), I often hear phrases along the following lines:

> [X] threw missiles

> missiles were thrown

This term 'missile' is something that's long struck me as unnecessarily obscure, and an excellent example of prioritising formality over clarity. Obviously it seems unlikely that what's meant by a missile is something produced by international arms manufacturers. It's unlikely to be something laser guided, heat seeking, carrying an explosive payload and so on. 

No, in this context a 'missile' is defined as:

> An object that is thrown. 

Which means the above phrases actually mean:

> [X] throw [objects that were thrown]

Or 

> [thrown things] were thrown

What's wrong with saying "things were thrown" when *things were thrown*? Why, instead, the convention to indirectly say "thrown things were thrown" using a term that on the face of it sounds more precise but which always seems never to convey any additional information in the context of the phrases in which it's almost invariably used? (As if it weren't thrown, it wouldn't by definition be a missile.) 

Are there *any* contexts or cases where the term 'objects' could not be used in place of 'missiles'? I can't think of any. 

