---
title: "Unpop"
listing: 
  contents: posts/unpop/**/**.qmd
  sort: "date"
  type: table
  fields: [date, title, reading-time]
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: false
---

## Introduction

I tend to take 'unserious' things seriously (as well as 'serious' things unseriously). Often if I'm watching, listening to or reading something, something nominally 'unserious' or 'lowbrow' or 'poppy', it will trigger a cascade of broader ideas, thoughts and concepts. [^1]

As well as an extensive series of posts on statistical theory, I've also written some posts inspired by various specific pop cultural artefacts, such as specific books, films, TV shows and games. In this section I've aimed to collate these disparate reflections into a single place. I've called it 'unpop' because - though many of the things I'm writing about are part of pop culture, I'm probably not picking them up when they're most popular, and neither am I treating them in a way that's particular conventional or 'poppy'. 

Often, the posts in this emergent series are going to be less technical than in the technical series. However, that doesn't mean I can promise these posts will be free of technical content, concepts or ideas. If you're scared of algebra, graphs, big words or code, this whole blogsite probably isn't for you!



[^1]: It's an occupational hazard of being me. 