---
title: "Mistaken (Aural) Identity: On podcasts and soundalikes"
date: "2024-08-12"
author: "Jon Minton"
categories: [podcasts, Liz Truss, the rest is money, TRIM]
---

Recently I was listening to [an episode of the podcast series](https://podcasts.apple.com/gb/podcast/stock-market-turmoil-is-it-time-to-panic/id1703785141?i=1000664684145) The Rest is Money, with Steph McGovan and Robert PESSSSS-TON. In this episode McGovan and Peston interviewed Karen Ward, which the episode blurb introduces as: 

> a Chief Market Strategist for EMEA at one of the world's leading financial institutions, JP Morgan Asset Management, as well as a former advisor to an ex chancellor

Now - as TRIM (as they probably like to call themselves) is a podcast, and I'm not much of an intrusive image search Googler - I have no idea what Karen Ward looks like. But I do have a clear idea of what she *sounds* like. 

Karen Ward, to my ears, sounds almost exactly like... Liz Truss. 

So, for 47 minutes, I was hearing someone who sounded almost exactly like Liz Truss. But who was saying things that sounded reasonable, considered, and intelligent. 

This experience created a weird kind of cognitive dissonance. Although I was consciously aware that Karen Ward was not Liz Truss, part of my subconscious was trying to simultaneously accept and reject the idea that 'Liz Truss' was saying sensible things about the economy. It was a much more bizarre and distracting experience than I was expecting. 

Now, back in 2001, when The Simpsons was still worth watching, there was an episode called [HOMR](https://en.wikipedia.org/wiki/HOMR). The episode was inspired by the short story [Flowers for Algernon](https://en.wikipedia.org/wiki/Flowers_for_Algernon), and is the one and only outing of a *smart* version of Homer Simpson. 

For those who've seen HOMR, when I was hearing the podcast, I was thinking: "Wow! Karen Ward is like Liz Truss with the crayon removed".


The deeper irony of this is TRIM, a few weeks previously, featured [an interview with Liz Truss](https://podcasts.apple.com/gb/podcast/the-liz-truss-interview-who-killed-liz-truss-part-4/id1703785141?i=1000654227719) of a similar length. Along with a mini-series about the Kwateng/Truss Budget, this is something for which TRIM got summarily review bombed. The Liz Truss interview, however, was much easier for my brain to cope with, because she kept saying very Liz-Truss-like things. There wasn't a dissonance to overcome! 


So, this got me thinking about 'soundalikes'. Is that a word? Does it need to be, given how popular podcasts are these days? What does it mean for one person's standing and reputation when they happen to have a very similar voice to someone with either a much better, or much worse, standing and reputation? 

The only previous time I've encountered something like the Truss/Ward soundalike dissonance is in listening to podcast interviews with [Daniel Schmachtenberger](https://civilizationemerging.com/). 

In brief: Schmachtenberger is a benign North American pseud. But he *sounds*, to my ears, almost exactly like [James Lindsay](https://newdiscourses.com/author/jameslindsay/), who's - without going into details - a *very malign* North American pseud.


Are there any lessons to take from this? Should people who happen to sound like annoying people try to change their way of speaking to reduce the possibility of mistaken identity? Should listeners whose brains flip when they hear these aural spitting images actually start searching for images of the two soundalikes so they should better distinguish between the two? Should we start listening to much more of both the annoying and non-annoying soundalike so we can start to tell them apart more easily? 

I don't know. I just know that, more than a week later, I'm still reeling from the experience!