---
title: "Three Computer Games for People who Don't Play Computer Games"
date: "2025-05-05"
author: "Jon Minton"
categories: [games, puzzles, stories, bank holidays]
---

It's a Bank Holiday. In my last few jobs - in the NHS, and in academia - Bank Holidays weren't taken off by default. But in my current job Bank Holidays *are* holidays, though for my partner Bank Holidays are not. So, when we're working differenet days, what better use of a free day than to bury oneself in a good game? Today I've mostly been playing a new game called The Blue Prince, which by no coincidence is a homophone on 'blueprints'.

Many people don't like computer games, both for good and bad reasons. Potentially good reasons include: the clear opportunity cost, the potential for motivation and energies that could be diverted more 'productively' to be instead vied to the mere shifting of electrons[^1]; the predatory practices involved in profiting from many modern games, and in some cases their blending into gambling mechanics, especially mobile games; their contribution to snacking and physical inactivity[^2]; the thematic preoccupation with violent power fantasies in many games. Some bad reasons include: the presumption that gaming develops no transferrable skills, and that gamers are mentally inactive; and that violent games lead to violent behaviour.

[^1]: Only a *potentially* good reason both because many forms of paid employment are, viewed from enough distance, also 'just' involve shifting electrons; and because similar opportunity costs are also present in many other, non-gaming and non-electronic hobbies, such as stamp collecting or going for hikes.

[^2]: Again, not necessarily different to many desk jobs, especially those that are fully remote.

Amongst non-gamers, some of the above arguments can be shields, psychological defences against the lurking awareness that, if they were to start playing most games, they would likely be terrible at them, unable to know how to jump, move, interact with items, react quickly enough to events, and so on, and so would feel humiliated. So rather than risk facing humiliation, they denegrate an activity worth billions of dollars, and that entertains and brings a sense of joy and meaning to hundreds of millions of people.

The barriers to entry are genuine, however, and as games become faster and - in *some* ways - more sophisticated, they lead to the cultural divides between gamers and non-gamers only growing, to lived experiences and sources of joy and purpose becoming mutually incomprehensible.

Blue Prince, whose main 'quest' I managed to finish today, is one of just three games I can think of, from the last 20 or so years, that I can recommend wholeheartedly to non-gamers. Each of these three games is very different, but each presents a comprehensive, joyous and enriching experience to players, which crucially does not rely on the level of kinetic fluency, the ability to decode events and react very quickly - required to even tread water in the majority of games. So in an effort to bridge the New Two Cultures - the separation between gamers and non-gamers - here's a brief overview of each of these three games:

-   [**The Blue Prince**](https://en.wikipedia.org/wiki/Blue_Prince_(video_game)): The Blue Prince was made largely by one person, Tondor Ros, who was inspired by an obscure 1985 puzzle book called Maze. The book was a choose-your-own-adventure story involving a mysterious house that can only be traversed by following a series of cryptic clues, in which the adventurer must reach the 46th room of the 45 room house. The Blue Prince takes this core premise and adds atmospheric sound and graphics, arcane storytelling, layers and levels of puzzlesolving, and most importantly *stochasticity*,[^3] meaning no game is exactly the same. The puzzles range from the clearly specified to the cryptically implied, from those which play out room-by-room to those which build up slowly across successive games, and from those that tax one's linear and logical faculties to those which require creativity and lateral leaps. And although demanding on those faculties that might be exercised by players of sodoku puzzles and cryptic crossword, there are no demands on dexterity or reaction time, and no violent or graphic content.
-   [**Disco Elysium**](https://en.wikipedia.org/wiki/Disco_Elysium): Disco Elysium is a 2019 adventure game produced by a small Eastern European games company called ZU/AM, and based on lore and ideas developed in a book called *Sacred and Terrible Air* by its lead designeer Robert Kurvitz, itself based on complex gameworld he developed with friends over many years. It is not just a game: it is narrative art. It is a rich, creative, undisciplined, cutting, poignant, elegaic, bittersweet book disguished as a game, and uses magical realism to try to make sense of the Eastern European sociocultural experience of the 20th Century: the state of being an individual in a state that is always acted upon by outside forces and political ideologies, that is predominantly object and not subject in outside battles. It is also the story of a broken man, haunted by the past, both guided and misdirected by a chorus of Jungian archetypes who swell up from within his psyche, and who forever try and pull the protagonist towards their ideals. In moderation, balanced out by other archetypes, each voice within can offer wisdom. But if one voice within ever becomes too loud then it drowns out its peers, leading the protagonist to pathology, embarassment and harm.[^4] Disco Elysium is the antidote to standard power fantasy cliches: the protagonist's present and future boxed in by the chains of their personal biography from before, by grand sociopolitical and even metaphysical forces acting from without, and by the chorus howling from within. Disco Elysium is set on another world, with a painterly expressionist style throughout and elegaic instrumentals swelling softly as our broken hero trudges through a quietly broken world. But in terms of its treatment of psychology, and politics, and the links between the two, it's one of the most realistic works of fiction I've ever encountered.
-   [**Plants vs. Zombies**](https://en.wikipedia.org/wiki/Plants_vs._Zombies): PvZ is a 2009 tower defence game. You are in charge of a house, a lawn, and some magical seeds, and you use the seeds to populate the lawn with various type of plant, with a view to holding off a very-slow moving, and very cute, zombie invasion. Although this is the only of the three games that can reasonably be described as 'real time', in that events occur to the player without the player causing them to happen, the pace is slow enough, and the controls simple enough, that the technical barriers to entry are very low. Of all the games I've ever played, PvZ is the only game my partner has played, and became enthusiastic about playing. For a few months many years ago, due entirely and exclusively to this game, my partner and I had gaming in common. What set up PvZ apart from other tower defence games includes the generousity and richness of what's included with the game,[^5] the comic premise and off-kilter humour, the gentle challenge of the gameplay, and the extremely charming music.

[^3]: The name for games that are somewhat random in this way, in effect procedurally generated, is *roguelike*. For those of a certain age and background, a good shortcut for understanding The Blue Prince is *Roguelike Myst*.

[^4]: And to the extent the protagonist can effectively die of shame, embarassment and harm can be one and the same.

[^5]: Though nongamers over the age of fifty might assume the most harmful aspect of games might be moral corruption due to interactive portrayals of violence criminality, I think a much stronger case is the introduction of *fremium* mobile phone games, in which an initially 'free' game uses full-scale psychological warfare to effectively 'trick' gamers into ploughing hundreds of pounds, micropayment by micropayment, into games seldom worth more than ten pounds. Unfortunately these highly predatory and dangerous games are likely to look amongst the least objectionable and harmful, and are often marketed towards children. When did the Fremium Turn begin? Sometimes between 2009, when Plants vs Zombies was released, and 2013, when Plants vs Zombies 2 was released. Whereas PvZ was for home PCs, so players had to make a conscious and sustained decision to play it, PvZ was mobile only, making it much easier to start a game almost without realising it. And where as PvZ cost a fixed price, and game with a lot of content, PvZ 2 starts nominally 'free', but after a few hours of play pesters players with adverts to new characters and areas, each time 'just' costing a pound or two. If the player doesn't part with real cash, the game then intentionally becomes tedious and bad until they change their mind. Between 2009 and 2013, between PvZ and PvZ2, the gaming industry's moral compass got replaced with a legion of barbed iphone apps.

So, three games I can recommend to non-gamers. Each accessible, each very different, each brilliant.
