---
title: "Counter Protests: Making a bad situation worse?"
draft: true
---

Over the last week or so there has been a worrying escalation of public disorder across (mostly) mid-sized Northern English towns. What seems to have lit the fuse is the appalling spree killing of three young girls, and maiming of many others, by a seventeen year old male in Southport. The age of the perpetrator is important, as this means he's considered a child in law, and so the official media are subject to a number of legal restrictions regarding the perpetrator's identity and details, which they would not be if he were aged eighteen or older. However, one detail that has been reported about the perpetrator is that he and/or his family are from Rwanda. 

The legal restrictions due to the perpetrator's age has led to something of a void of official detail about identity and motives, whereas the horrific nature of the crimes has created a strong demand to know those same details. And into this void it appears social media, a law unto itself, has stepped in, with angry speculation that the official media is legally prohibited from either confirming or denying. The kinds of speculation that have gained most traction appear to be those that appeal to the prejudices of certain especially prejudiced members of society, namely down-at-heel racists and xenophobes inclined to blame migrants for their own general misfortune. 

They also blame Muslims, which seems strange not least because [only around 2% of Rwandans practice Islam](https://en.wikipedia.org/wiki/Islam_in_Rwanda), which is a majority Christian nation. And so over the last week or so angry and violent racists and xenophobes have ... 