---
title: "It's your choice"
subtitle: "A bureaucratic satire featuring three men, two gods, and one chair"
date: 2025-07-28
author: Jon Minton
categories: [fiction, satire, thought experiments, justice]

---

## Waiting Area

Jim puts his head in his hands. Or at least he tries to. The hands don't quite reach, arrested by the chains. 

Jim lowers his head to his hands and groans. 

The noise, all around, bad at the best of the times, and this isn't the best of times. Noise, noise, noise from without, noise from within. 

Jim doesn't know why he's here. Or at least that's what he tells himself. Part of him - his guts, his spleen - knows *exactly* why he's here. That's why the other bits of him, the mouth and the tongue and the neck and the skull and the throbbing grey goo inside, would rather not listen to the insistent noises below. 

"10872!". A languid voice bellows with an indignant, officious tone. "10872!"

Jim remembers the coupon scrolled in his hand. Unfurling. Tongue moves softly, tracing the digits. 

"won... oh ... ate... seven... too!"

Jim stands, steps forward, trips over. Skull falls onto stained cyan carpet. 

"You have to wait for an officer to unlock you," the voice at the desk drawls. "We're not exactly free range here."

Jim pulls himself back into a jangly ball, pivots himself against the front of the bench, and hops to a stand. 

The polyester shuffle gets louder, becoming a ring of keys. 

"10872?" asks the mouth behind the ring. 

"Erm, yeah!" confirms Jim. 

"Up a bit." Sleeves gesture at hands. 

Jim obliges.

"Wait a bit. Hold it." A tongue appears in the corner of the mouth. The keys start to circle around the ring, each engraved number scanned. "I think it's this one," says the mouth to itself. The ring is thrust, index key first, into Jim's cuffs. "Hold it!", the mouth repeats. 

Twisting, grabbing, pushing, prodding. Then a turn. The tension drops from Jim's wrists, from the cuffs to the ankles to the back of the bench. 

"Follow me".

Jim shambles along in the mouth's wake. 

"Is this an office or a jail?" Jim wonders to himself. 

"Both," answers the mouth. "Back in the day, just an office. Then there was that whole work-from-home craze, and then for a while it was nothing. Then it was a squat. And then it was ours."

"Sorry, I didn't realise I asked that out loud."

"Your lot often doesn't."

*My lot?*, wonders Jim.

"Anyway, of course the squatters didn't want to leave." The mouth licks its lips. "But then once they'd been convicted, they ended up here. And then the didn't want to *stay*!" **Bronchial spluttering**. (Silence)

(Silence.)

(Silence.)


"Case adviser's in there," says the mouth. The polyester straight-arm salutes the door of an office in a box. 

Jim looks at the mouth and the uniform. 

"In there," says the mouth.

Jim shambles *in there*, pushing open the door by knocking against the kickplate.

## Outer Room 

"Come in!" says the box's occupant. "Come in! Come in!" A smile. Genuine. (You can see it in the eyes. And hear it in the voice.) The occupant wears a shirt, short-sleeved, crinkling slightly as he moves. Glasses, wire-framed. A moustache that looks like it used to be more distinctively zoned, whose boundaries are fuzzier against a half-week's growth of pepper-grey hairs on cheek, chin and neck. His build is on the hard edge of soft. From his skin the man looks to be in his late thirties, pale, red threaded. 

"Take a seat," says the man, gesturing to a worn swivelchair. 

Jim obliges. 

"Hi!" says the man, extending his hand in greeting. "I'm Kevin; and I'll by your CDSO during your visit here."

"What's a CDSO?" asks Jim.

"Sorry for the ETLA," says Kevin, chuckling lightly to himself. "Case and Decision Support Officer."

"Oh," says Jim, seated. 

"So," says Kevin. "Have you thought some on The Decision? Any preferences? *TBJ*, or *TBO*?"

"What?!" exclaims Jim. 

Kevin looks at Jim for a second. "You really don't know. Haven't you been following the news for the last couple of years? It's been the big flagship policy the current lot came in on."

Jim looks blankly. 

"You really don't know, do you?" Kevin pauses, recalling the form of words. "The TBO initiative was introduced to improve criminal justice outcomes for the three main stakeholders in our sector: the victim, the perpetrator, and the taxpayer. As I said, it's the current lot's big idea, and very popular with voters. After they did the pilot programme over in Northern Ireland they mostly sorted out the wrinkles and it got rolled out nationwide. And over there, next door, I'm pleased to tell you we've got one of our brand new TBO units, last safety inspection just six weeks ago, all prepped and ready to use." Kevin pauses. "If you go for the TBO path, of course. *It's your choice*."

Jim looks more carefully at the room they're in. Beyond and facing the nondescript office door he entered the room through is a second, much sturdier door, metal, by the looks of it much thicker, looking a bit like something that fit in a bank vault or a submarine. 

Jim first realises that the room they're in is more wide than long, as if it were just one third of an initially cuboid space. 

Jim looks now at the wall in which the vault-like door is inset, and from the sturdiness and apparent thickness of the inner door infers that the entire wall is much thicker than the wall containing the office space. Jim notes that the vault-like door is inset slightly against the apparent contours of the wall, and from this infers that the inner wall itself is covered by a thin facade, chipboard perhaps, which has been papered and painted the same light green as the other three walls of the drably officious outer sanctum he currently understands himself to be sitting in. About halfway along the width of the wall, and about two fifths of the way down the wall, Jim sees a light curtain rail from which some light crimson drapes are suspended. Jim thinks he can make out some rivets recessed slightly behind the drapes.

"Yes!" says Kevin. "It's all over there. We're an integrated service here. Just a one minute walk, no delays."

Jim turns back to face Kevin 'behind' the small desk. A very small desk, in fact, more like a coffee table, round, slightly to one side. On this small desk: a charging stand with a rubber-enclosed tablet computer, and a squatter, wider stand with the following words written, by the looks of it, in some professionalised derivative of comic sans. 

> Kevin Peterson, PhD
> Senior Case/Decision Support Officer


"What's a per-her-der?" asks Jim.

Kevin grins. "Pee aitch Dee." He pauses. "A doctorate (Too much time in school.) I got it in criminal psychology, about eight years ago. Back when a lot of this stuff was more theoretical."

"Oh," says Jim.

"Anyway, enough about me. This is *your* meeting. I'm here to support and guide you through your Criminal Justice Journey. This meeting is *your* meeting. It's *your* Decision."

"My decision?", asks Jim.

"Yes." Kevin exhales, then speaks more slowly and clearly, as if to a child or an invalid. "*TBJ*... *or*... *TBO*?" Kevin waits and stares.

Jim blinks. 

"Let's get your case file up..."  Kevin picks up the tablet and starts prodding. After a few seconds he stops, eyes saccading, frowns, and forces his mouth back upright. 

"So..." Kevin speaks deliberatively. He inhales. "You're 'accused' of killing a cat, last night, at 1:03am, on King Street. As well as the usual drunk and disorderly."

Jim's eyes widen and start to tear up. "I'm accused of doing *what*?!" he exclaims. "But I love cats!"

"I said 'accused' with inverted commas," Kevin clarifies, this time quivering the first two fingers of his free hand, like bunny ears, while saying 'accused'. "With my TBO hat on, and my very similar looking Common Sense hat on, I can just say this: You killed a cat. You've done wrong. How are you going to make this right?"

Jim realises that Kevin's face is now less than two hand lengths from his own, as with each of the previous fifteen words Kevin had heanty ever closer towards Jim's eyes. Jim can smell the tuna sandwich that Kevin had for lunch. 

Kevin straightens and backs up again, returning to a more comfortable distance. "Of course, from the TBJ perspective, you're just 'accused' at this stage. 'Innocent until proven guilty', as they still sometimes say. But we've already got..." Kevin scrolls down on the tablet. "... three eyewitness statements, two Ring camera records (with audio), and blood and fur samples recovered from your right shoe and tracksuit bottoms."

Only now does Jim realise he's wearing open sandals he's never owned, and this his trousers appear to be made of thick green paper. 

"And of course," Kevin continues, "we've got this recorded by the arresting officer at 1.42am last night..." Kevin jabs a button on the tablet. 

"Oh my God!", cries the tablet in Jim's voice. "I've killed a cat! I've killed a cat! What the hell have I done?! I've killed a cat!"

"But of course," continues Kevin, "statements made by intoxicated individuals aren't considered especially high quality evidence. In isolation, it wouldn't have been enough."

Jim is a quietly heaving, deflated thing, arms draped awkwardly, face to floor, back round and quivering. 

Kevin waits momentarily. "So," he begins, "to repeat, you've basically got two options. (Well, technically two-and-a-half, I guess, but anyway...): You can go down the TBJ route, where you're 'just accused' of all this (or you could plead guilty, the half option, but that's not really too different to the TBJ path in practice). Or you could go down the TBO route, where you accept you did it, and it can all be resolved in the next hour."

Jim arrests his sniffles and raises his head. "Wait... what day is it?"

"It's Sunday, James."

"Shit!", says Jim. "I can't miss work tomorrow. They'll fire me."

"Well," says Kevin, "in that case the only chance you've got of getting to work tomorrow is the TBO route. We're looking at a... "  - Kevin prods the tablet - "... 22 month delay for trials."

"And if I just plead guilty?"

"Even that's quite backed up too. Currently we're looking at a ... " - more prodding on the tablet - "13 week delay to see a circuit judge to hear the plea."

"Could I work while I wait?"

"We don't do that anymore." Kevin shakes his head. "You'd have to spend the wait in jail. Currently things are getting a little better there. You'll be looking at.." - more prodding - " 1.13 square metres (estimated average stay) to yourself while you're with us. And you'll be sharing a latrine with just 41 other guests."

Jim pauses. In a half whisper he says, "I'll pick TBO."

"What's that?" asks Kevin. 

"I'll pick TBO. I *did it*. I'll choose TBO. I'm *choosing* TBO. Thank you!"

"Great!", exclaims Kevin, jumping to a stand. "Let's hope Algos and Stochastos are smiling today." Kevin winks. 

"Who?" asks Jim. 

"The gods, Algos and Stochastos. Though they might sound a bit foreign they're proudly made in Britain. First we've got Algos. He listens and weights..."

"Waits for what?" asks Jim. 

"Not *waits*," Kevin chuckles. "Weights! As in, like heavier or lighter, more weight to *this* side, or to *that* side. Algos, you see, he's fair, and he listens. He listens to *The Chorus*, fifteen freshly picked members from the Good Citizens Panel. They look, they hear, they have a quick think, then they tell Algos what they reckon about what they've seen and heard."

"Fifteen, like a big jury?"

"Technically a Chorus isn't a jury. But they do have a quick look at some materials and try to answer and grade some questions. But unlike a jury they just tend to focus on grading the State's evidence, rather than listening to those overpaid fools in white wigs drone on for days and weeks on end, and the witnesses getting asked silly questions by the white wig brigade." Kevin pauses. "That way, the Chorus can usually get set up and grading done in under an hour, sitting in their dressing gown over a glass of red wine at home. It's so much more of an efficient system than the old jury way of doing things."

Kevin looks some more at the tablet, scrolls up and down. He looks at Jim with a wide smile, almost giddy. "And I'm pleased to tell you that the grading for your case has already been completed, and told to Algos, all while we were having this chat. The Chorus spoke, Algos heard, and the weighting's been finalised. Now it's just over to Stochastos for the final stage. Over there please!" Kevin gestures to the vault-like door. 

Jim stands, walks over, and reaches for the thick door's handle. 

"It's open," says Kevin. "Just give it a light push."


Jim does as instructed. The heavy looking door glides about its axis almost effortlessly. Jim takes a couple of tall steps to clear the threshold.


## Inner Room 

Inside, the room is covered - floor to wall to ceiling - in white tiles, with harsh, uniform lighting. The dimensions of this inner room are like those of the outer chamber, only a bit smaller, implying all walls of this door are of similar thickness to the vault door entrance. On the narrowest wall to his left a dark inset glass-like bulb is visible, jutting carefully from the wall. Something inside the bulb whirrs and lights up. A camera, operated elsewhere? Facing this presumed target-hardened camera, at the far side of the room, is a strange contraption of many parts. 

At the top of the contraption is something like looks like a modified bicycle helmet held up by a thick, horizontal grey tube, coming out of the otherwise featureless wall to the left from Jim's view. The helmet appears complete along the far side (the tube side), but parts are missing along its other side. Instead it looks adapted near the front and back to hold a currently loose, dangling pair of straps. 

Below the modified bicycle helmet is something that looks like a patio chair with arm rests. The chair sits atop a height adjustable circular column, at the base of which are four concrete 'feet' which step astride - what is that? a gutter? - cutting deeper, and wider to the right than the left of the footed 'pillar' on which the seat sits. From Jim's current position it's difficult to know how deep the gully goes. 

"There it is," says Kevin, "Where Stochastos does her thing. Walk towards it. Check it out!"

"*Her* thing?" enquires Jim, stepping towards the garden throne contraption with a dream-like cadence. 

"Call her Lady Luck if you like." Kevin's smile radiates through his voice. It sounds... warm. "Stochastos is her *Sunday Name.*"

Jim is now less than a metre and a half from the other end of the wall, and can see more of the Garden Throne and the gutter on which it bestrides. Now he can judge the depth and contours of the gutter more accurately. It almost looks like a sink, except inset into the ground, and instead of the back end finishing with a straight edge, it stetches back, under the four concrete 'feet' of the Garden Throne pillar, like the tail of a stingray. 

Jim notices another feature on this end of the room. Opposite the bicycle helmet/tube contraption, on the opposing wall, an additional extra large, extra thick ceramic tile has been slotted against the wall, held in place by metal grooves on each side and below. The centre of this extra large, extra thick tile faces the centre of the tube holding the bicycle helmet. 

"Take your throne," says Kevin. "And I'll adjust the height."

Jim obliges, placing himself on the metal seat. There are arm rests with straps either side. Jim's feet initially lay on the tile floor. Instinctively he swishes his feet forwards and backwards, like a child trying to escape gravity momentarily on a swing. 

"For your safety," says Kevin, "please place your arms within the security straps on each arm rest."

Jim notices the arms are on top of the straps. Awkwardly he rearranges his limbs so the straps are above and the rests below. 

"Now let's get the right app up." Kevin looks down at his tablet and swipes a few times, the edge of his tongue poking out one side of his mouth. "Ready now." Kevin makes an assertive prod on his screen. The arm rests whirr and the straps tighten. They have some give, but not much. Jim now notices the impression of something, circular, indented, with a bit of give, beneath his right hand. 

"Now let's get the elevation sorted. (Unfortunately we can't do pitch and yaw with this hot seat.)" Kevin chuckles to himself, stabs at his tablet. Servos whirr from below. Jim's body shoots up, the top of his skull dabbing and now pressing, slightly uncomfortably, against the top of the helmet. 

"This bit's still manual. Let me help you." Kevin walks up to Jim and the chair, his attention focused on the half metre strap that hangs and dangles from the pipe-end of the helmet. The tongue pokes out of the side of Kevin's mouth again, and his brow furrows, as he reaches for the strap. "Hand-eye coordination. Never my strong suit." Kevin mutters to himself, as he pulls and rotates the strap below and around Jim's head. "Got it!", Kevin says. The strap loops back down, back around Jim's chin, and is secured a second time at its origin point. Kevin pulls down. Jim feels his head's mobility has become much restricted. "Great," says Kevin. "Safe and secure." Kevin walks back and admires his manual labour. 

"Now the next step: We just need to let the D Team know we're ready for them." Kevin pauses. "Luckily that's just a button press as well, much like ordering a pizza." Kevin looks at his tablet again, saccades, scrolls, jabs a couple of times, then theatrically moves his hand back, extends his forefinger, and presses firmly on the tablet one last time. Then, a couple of seconds later, he looks left, to the side of the room they did not enter from. Jim tries to do the same, but with his head secured only his eyes move. 

Muffled sounds appear from behind the wall. It appears to be a conversation, though Jim cannot make out any words. Jim listens intently. The cadence sounds like a series of questions being asked, then answered with a simple affirmative or negative. The exchange lasts about twenty seconds. Then there is a pause, and then.... 

**Crunch! Thud!**

**Crunch! Thud!**

**Crunch! Thud!**

**Crunch! Thud!**

**Crunch! Thud!**

**Crunch! Thud!**


Six times! Each noise appears twice to Jim's ears: in a muffled form, through the wall, to both ears. Then in a fainter, tinnier but oddly clearer form through the tube, through Jim's right ear only. The sounds are ever so slightly out-of-sync, through clearly have the same origin. 

"And six." Jim notices that Kevin has been counting to himself. He's smiling. Radiant with happiness even. Kevin notices that Jim has noticed him and offers a conspiratorial wink. 

Kevin looks a picture of controlled mania in his expression, which he refuses to hide from Jim. "Unfortunately for this last big I've got to go back over there." Kevin gestures at the room they came from. "Health and safety", Kevin continues, as if quoting more than saying. "Ear damage," he continues. "I even offered to sign a waiver..." Kevin drifts off. "But anyway, I've got to go back there."

"Um, okay", says Jim, trying to nod reassuringly, despite the strap under his chin. 

Kevin makes a sheepish half-bow and steps back, turning and walking to the door, glancing back as he touches the handly, taking a cautious up-step to clear the threshold, bowing again through the door, turning, pulling the door through on the other side. 

Jim hears the **klang!** of the door shutting, then the metallic scraping of the door mechanism being turned shut. Jim then hears some distant footsteps, behind the wall, moving towards him. Then he sees the curtains open up behind the viewing port. Kevin's eyes are now looking at him behind the glass. 

The eyes look down and sway slightly. A static jolt sounds through the room. Kevin's voice follows.

"Hi Jim! Now, for this last bit you've just got to do a couple of things..."

"Erm, okay!" says Jim. 

"Firstly, you should be able to feel a couple of things with your right hand. A couple of square-topped plastic things. You should just be able to see these too. They're button covers."

Jim glances down and feels with his hand. As described, both buttons are visible, both under clear plastic caps. Both buttons are lit from within, a bit like those fruit machines Jim remembers seeing in a museum. The left button is amber, the right button is red. Currently the left button is lit, shining a solid green light.

"The cover for the left button should now be flippable. Just take your first two fingers and feel for a catch just before the button itself. Press the catch in a bit and the cover should flip up, letting you press the button itself."

Jim pauses. "Okay?"

Kevin pauses. "So can you press the catch release please?"

Jim does so. The catch springs up and away, revealing the green button as described. 

Kevin's mouth is not visible, but Jim can see from his eyes that he's smiling. The tone of the voice in the intercom confirms this. "I'm sure you can guess the next step..."

"Open the other cover?" Jim asks. 

"I guess I was wrong. No, next step is you *press* the green button."

"Right. Sorry." Jim's forefinger reaches for the green button. Just like that antique fruit machine he feels the plastic surrounded by the metal ring. He presses the centre of the flat plastic surface down and feels a reassuring click. The light on the button changes instantly, from solid to flashing.

Then Jim hears something to his right. A rumbling rotary noise, clanging into action the moment Jim first pressed that button, then after a second whirring with what sounds (and feels) like an accelerating cadence. After about three more seconds the whirring sound has become a constant hum, speeding up no more. Jim listens to the rotary noise briefly. The hum flitters almost hypnotically, oddly reassuringly, almost a single tone, but not quite. Cycles within cycles. 

"Great!" says Kevin through the intercom. Speaking with deliberate enunciation he continues. "Now just two last steps: open the right button's catch, then press the button."

Jim's middle finger reaches for the cover catch on the right button's cover, and presses down. Just like the first, the second button cover releases up and over. The unsheathed button is now flashing between two intensities of red light.

"Now press the red button. Or don't. *It's your choice!*"

Jim presses the button 