---
title: "Weaponising the Empathy Machine: On Escape at Dannemora"
author: "Jon Minton"
date: "2024-12-30"
categories: [prison, crime, escape, empathy]
---

The film critic Roger Ebert [famously described films as 'empathy machines'](https://www.rogerebert.com/features/memoriam-feature-2023), and indeed they are. The combination and synchronisation of sight and sound, and over a century's development and refinement of techniques for conveying a sense of 'being there'- from shot/reverse shot onwards - means perhaps there is no other medium in which the sense of feeling embodied and experientially coterminous with a protagonist is so effortless for a viewer to experience and, for better or for worse, so difficult to resist. 

In [Brave New World](https://en.wikipedia.org/wiki/Brave_New_World), which extrapolated and parodied the sociological consequences of then-emerging early twentieth century technologies, the utopian successor to 'movies' are called 'feelies', in which this sense of experiential coterminousness reaches its theoretical apex. Though we do not use the term, many contemporary films, especially those which place theme-park-ride-like spectacle over conventional narrative structure, are already in effect 'feelies', even if in such cases the intent is more to make the viewer *feel*, rather than *feel like* any of the film's protagonists. 

By convention movies and television aim to promote empathy towards the protagonists, who are heroic, and enmity (reverse empathy) towards the antagonists, who are villainous. But this choice of in which direction to fire the empathy machine is ultimately just a convention. Films and television can choose to bring an equinimity of empathy to characters whose aims are in conflict with each other: both 'cop' and 'robber' in [Heat](https://en.wikipedia.org/wiki/Heat_(1995_film)), for example. But generally, empathy is directed and hoarded, not radiated and shared. Showing empathy for all characters in a story, whose aims are in irreconcilible conflict, can bring to the viewer the realisation that reality, itself, is fundamentally tragic: there is seldom a clear choice between good and evil, so much as a need to constantly try, and often fail, to find the lesser of two evils. Films that share the empathy too widely, and show both the light and darkness in all conflicting parties, tend to win awards but not viewers, who would rather feel only happiness for the eventual victor, without also experiencing the heartache of the loser. 

All of which is a preamble for sharing my thoughts - and feelings - on watching [Escape at Dannemora](https://en.wikipedia.org/wiki/Escape_at_Dannemora), a 2018 true crime biopic based on [a (partially) successful prison escape in 2015](https://en.wikipedia.org/wiki/2015_Clinton_Correctional_Facility_escape) (and seemingly about the only newish programme on Paramount+ that's not about cowboys). The mini-series makes great use of the convention of the programme format, of being around six to ten one hour episodes long, and quite slow, to play with and weaponise film as an empathy machines. 

In stories of David vs Goliath, of the man against the machine, of the few against the many, there's an overwhelming instinct to side with the underdog. And indeed over half of Escape at Dannemora - the first four of the seven episodes - seem devoted to telling the story of the escape, its meticulous planning and execution, very much from the escapees' perspectives. We can't help but find something about the escapees' fortitude, initiative, resilience, creativity and grit admirable, even inspirational. 

But, though Escape from Dannemora is a programme of seven episodes, it's more fundamentally a programme of *three sections*. 

Section one comprises the first four episodes, as mentioned, tell the story of the planning and execution of the escape. And as mentioned, the viewer can't help but empathise strongly with the escapees. 

Section three comparises the last two episodes, which document the authorities' attempts to recapture the escapees. 

And between the first four episodes set before the escape and the last two episodes set after the escape, is section two, comprising a single episode: episode five. And episode five isn't set *before* the escape, or *during* the escape, but *way before* the escape. Episode five shows, after four episodes developing empathy for the two main protagonists, exactly why that empathy may be misplaced. Episode five shows, in graphic detail, why the prisoners, whom the show has been implicitly encouraging viewers to will and wish out of prison, are in prison, and *deserve to be* in prison. 

So, episode five, section two of the three section series, turns the first four episodes of the series, section one, into *an empathy trick*. And because section one comparises four of the seven episodes, episode five therefore turns the majoarity of the programme itself into an empathy trick. By episode five, the viewer - like another of the key protagonists - was seduced by two barbaric murderers into feeling that they're *the good guys*, and that the aspirations and aims of the protagonists are coterminous with that of the viewer. 

Film and television are empathy machines. And to my mind no television show has been more effective and masterful at weaponising these machines to play an *empathy trick* on its viewers. It got me right in the feelies. And then it got me. 





