---
title: "The Wristwatch"
subtitle: "My late father's magic trick"
date: '2024-11-21'
categories: [nigel, psychology, sales, tricks]
---

[My father's funeral](../book-of-nigel/index.qmd) was on Monday (18 November, 2024), around one month after his death. Well attended, well loved, well remembered, sorely missed, my father was 'a gentleman and a gentle man' according one of the eulogies. And that he was. 

But he wasn't *just* this, and he wasn't *always* this. If he were, he wouldn't have been as effective in work and enterprise as he was. He was in positions of authority and responsibility long and often enough to have needed to make decisions that, at times, favoured some people over other, and as a result would have upset some of his colleagues and subordinates. Gentleness alone wouldn't have been enough to have made the man, even if it makes for a fitting eulogised paragon to shine briefly in the shadow of a man's wake. Even in retirement, he was the volunteer at one of the charities he joined who tasked himself to wind down the charity after COVID, lest it haemorrhage funds and accrue even more catastrophic debts. 

Before starting university, to do a degree in engineering, there were plans for me to do a year in industry, to get practical experience, and funds, before the university education began. Rolls-Royce was by some margin the largest local industrial employer in the area, and also where my father held a senior management role in 'human resources'. [^1] I remember attending a student-employer matching event. The Rolls-Royce representative at the event invited me into the office he'd requisitioned. He had an off-kilter glint in his eye and a broad but asymmetric smile. He pointed to my name on his sheet and asked me if I was the son of my father. I confirmed I was, and asked if they knew each other. "Yes we do", he said. 

[^1]: A strangely anti-euphemistic and accurate term, in favour at the time. 

After the event I mentioned the representative's name to my father. "Oh no!", he said. "You're not going to get an offer of placement." Apparently the representative had a vendetta against my father, resulting from my father passing him over, possibly more than once, for promotion. And indeed, my father's prediction came to pass: I didn't get an offer of placement. This Rolls-Royce representative had such an animosity towards my father that he took pleasure in using me as a pawn with which to try to hurt him. The representative's career ambitions was an egg my father found necessary to break to do his job well, and he could not have done this job well if he were too gentle or gentlemanly to break it. 

I really don't think my father liked conflict, however. I believe he preferred to *manage* people, in various subtle ways that upped the odds that he got what he wanted from them, and they felt they got what they wanted from him. 

Which brings me to the wristwatch. 

For most of his career, my father, who was right handed, wore his wristwatch on his *right* hand, facing *inwards*, rather than the standard way of wearing a wristwatch, which is on the *left* hand, facing outwards. So, whereas with the standard, left-hand out-facing positioning, the watch's face is upwards when the hand's palm is down, with my father's unorthodox right-hand in-facing position, the watch's face is *downwards* when the hand's palm is down. One implication of my father's unorthodox positioning is that the watch face is more likely to become scuffed on tables and desks. So why did my father wear his watch this way? 

From what I understand, my father picked up the flipped wristwatch habit when he worked as a salesman, selling gas boilers in (I think) the 1960s and 1970s. He retained this habit, however, in middle and senior management roles in the 1980s, 1990s, and 2000s, and (I believe) only retired this habit around a decade after he himself retired, perhaps at some point in the 2010s. The flipped wristwatch habit sustained itself for decades, so it must have had some benefits, which more than outweighted the higher potential for scuffed faces. What could they have been? 

Let's start at the start. You're selling gas boilers door-to-door. Gas boilers are a major investment for potential customers, something they're only going to agree to if they trust the salesman implicitly to listen to them and their concerns, to be, and be seen to be, fully *present* in any conversations about this potentially transformative (and, involving an invisible, toxic and flammable gas, potentially dangerous) investment. The salesman knows this: he's got to seem trustworthy and present. But the salesman also knows that each person he talks to in this capacity is really 'just' (there's that word again) a 'mark', a 'prospect', which *might* result in a big sale, and so commission, but also probably won't. And so, for a prospect that doesn't pay out, each minute spent talking to the person is a minute wasted. 

And so, the salesman knows he has two apparently competing requirements for doing his job well: Firstly, to appear to be fully present in any conversations with potential customers; to appear to be fully attentive, engaged and listening to the kind men and (possibly more likely) women who have generously agreed to let him into their home. But secondly, to always know what time it is, and be aware of exactly how long has been sunk into each of these marks, and so when it might be better to cut one's losses, thank the potential customer for their time, and leave for the next prospect. 

Now imagine how to address these competing requirements with a wristwatch in the standard, left-hand out-facing, position. You're sitting down with the potential customer, maybe across a dining table. You get out and lay out your brochures and other sales materials, and you sit and hold yourself in an open and friendly way, perhaps loosely mirroring their body language, but more importantly adopting an open posture while sitting, arms held wide, and *palms facing up* while gesticulating and explaining the wonders of the new system you're hear to talk about. 

Now imagine, with the wristwatch in the standard position, you check the time. This involves flipping your left hand nearly 180 degrees. For the potential customer, it's a very obvious *tell*, making the subterfuge of appearing fully present all too clear. So suddenly, with the flick of a wrist, the potential customer knows that she or he is just one of a number of your potential prospects, and you're trying to work out whether to pull the plug on your time together, and that you're definitely *not* fully present and attentive to you regarding this potentially life-altering decision. With a flick of a wrist, which you need to make to tell the time, you could have lost a big sale. 

Now rerun the scenario with the unorthodox wristwatch position. You're sitting down, explaining things, your palms are open, upward, fingers grasping, pointing, gesturing. As you reach with your right hand for a prop, maybe a gas safety feature used to explain why it's not possible that the device will poison the potential customer in their sleep, you happen to glance at your wrist. And so, *you now know the time*. But more importantly, you know the time without the potential customer having clocked onto your having looked at your watch. For almost everyone, the act of checking the time with a watch is a flick palm downwards of the left hand. And you didn't do that. Of course, the wristwatch isn't physically invisible. But as the potential customer wasn't looking for it, psychologically it may as well be. With the flipped wristwatch position, you can square the circle, balancing the need to appear fully absorbed and present for the prospect, with constant awareness of the time invested. 


Now imagine you're no longer in sales, but management. You have meetings. Lots of meetings. Some people tend to take a long time to say very little. Some one-to-one meetings are of a sensitive and personal nature, perhaps about challenging and traumatic experiences and events (such as the death of a parent), and for these people, especially, you need to appear fully present. But you've also got other meetings. How do you know *when* you should try to encourage the person you're meeting with to start to think that maybe it's their idea that the meeting is coming to a natural conclusion? Once again, the surreptitious, incidental right-wrist glance of the reversed wristwatch comes to your aid. Again, and again, and again. 


As mentioned, the reversed wristwatch trick was something my father eventually retired. But it took a long time. It was an eccentricity, an idiosyncracy, that to the uninitiated appeared 'just quirky', but actually resulted from years of experimentation, calculation and practice in subtly tipping the scales of professional interpersonal interactions. Gentle and gentlemanly behaviour, I don't know: It was brilliantly, beautifully, *sneaky*. And it was one of many, many facets that made my father who he was. 

