---
title: "Wham! forever: On cultural debraiding and the end of Cultural progress"
author: "Jon Minton"
date: "2024-12-21"
categories: [social media, culture, christmas, music, fashion, progress]
---

## Wham! (again)

[According to BBC News](https://www.bbc.co.uk/news/articles/c9dp6y31qppo), Wham!'s single, Last Christmas, first released in 1984, is now Christmas Number One for 2024, as well as having previously been the number one single last year as well. The 40 year old song isn't even the oldest entry in the top ten, with other entries including Rockin' Around The Christmas Tree (1958), and Jingle Bell Rock (1957). 


## The 'Charts'?

If music pundits from the 1980s or 1990s were to have access to the Christmas Number Ones from today, and the last decade, they would likely be surprised, especially if album or single sales were taken into account. Something strange has happened, profoundly strange, given both how much familiar and repetitive the entries that keep appearing in these lists are, and secondly likely by how few records have been bought and sold. 

Part of the reason for this strangeness from an 1980s or 1990s perspective is that the Christmas Number One chart is itself profoundly anachronistic. Very few songs are purchased as records, housed in physical information storage devices (vinyls, tapes, CDs and so on), which the purchasers then own. Instead most of these 'sales' comprise 'streamed listens', the number of times a device from a streaming service to which people subscribe, like Apple Music or Spotify, is beamed to that device and emanates through often small and tinny speakers. At Christmas time, more of these users are likely to select playlists of Christmas Songs, and its on these playlists that these decades-old songs are included. To continue producing song charts, various tariffs or conversion factors are employed: the streaming of a given number of songs from an album a given number of times is considered *equivalent to* the purchase of that album, even if the subscriber to the service isn't even aware of the album's existence, and neither seeks out or hears many of the songs on the album. For singles the need for conversion factors or tarrifs is less, though there are likely issues of equivalency when different versions of the same song are streamed. Instead a song is more likely to reach a top ten spot mainly by dint of being included in a larger number of more popular playlists. Again, the listeners take a more passive role in the proceedings: after initially agreeing to purchase a streaming surface the subscription payments are automated, and the 'choice' to listen to Wham!'s 1984 classic can involve as little as tapping a couple of buttons on a phone, not even searching for this particular single. 

## The New Normal

The thing is, for most of us living through the last five or ten years, none of this is at all surprising. It's simply how things are now. For anyone younger than middle-aged, the very sense that things were ever not thus is at most a distant and unreliable echo of a memory. Even cinephiles who used to have shelves full of VHSes or DVDs, or audiophiles whose shelves strained under CDs and vinyl records, are likely - some hipsters notwithstanding - to have sold most of their physical collection at a small fraction of the purchase price in exchange for a monthly subscription service to a tech behemoth. At every stage, in every way, the streaming service was just more *convenient*, the once essential effort of having to make a choice of an album and the labour involved in removing a CD from a player (and worse, having to find the CD case that contained it) and replacing it with another one, all spontaneously considered and discovered to be activites simply too effortful and involved to stick with. Even if, over the course of a few months and years, the results of moving from owning to renting access to music meant spending hundreds or even thousands of pounds with nothing in the long-term to show for it, the *convenience* of not having to decide what to listen to, and of reducing one's affordances with music technology - from looking, opening, extracting, pressing and turning; to tapping and prodding on a single screen - has made the transition almost thoughtlessly easy and complete. 

But that transition happened over a decade ago, with the introduction of smartphones - cultural Everything Devices - in the late 2000s. The transition - from owning to renting, from matter to electrons - was a profound shift in *how culture is experienced and consumed*, but is not in itself *a cultural experience*. There is nothing intrinsically uniting about *what* people experience and consume when they use smartphones and streaming services, just a similarity in *how* people receive media. 

## The Decades that Time Forgot

Which brings me to [this argument](https://www.youtube.com/watch?v=NkAJtRiOAxk&t=14s), made by comedian Michael Spicer in a video called 'Nothing has changed since 1999'. Although presented with a comic spin, and containing a number of skits, the argument itself appears to be serious:

> The early 2000s were really weird. And what's weirder about them is they haven't gone anywhere. We are still living in the early 2000s. Nothing's changed. Nothing's shifted. Nothing's moved forward. 

> There's no such thing as a dead genre of music. ... And this is the crux of why nothing has changed culturally in the last 20 years. Because the internet, and social media, has seen to it that every single group, no matter how small, has their space online. There's no underground anymore. There's no overground. It's just everything, everywhere, all at once (!). 

> So, the world is not going to be gripped collectively by a cultural phenomenon anymore. Whether that's TV, music, fashion or film. That is over. You are not watching, or reading or listening to the same things that I am. We can just split off and absorb whatever we want online. We're not limited to one particular cultural shift. The days of everyone in the country sitting down to watch the same programme at the same time every week are gone. 

> We don't experience culture collectively anymore. We branch off in our own little pockets of interest. And that's why, weirdly, it doesn't feel like we're moving forwards. We're moving forwards in terms of techological advancement. But in terms of culture we're just... floating. 

> That's why you can watch a film from 2004 and it won't dawn on you that it's twenty years old until you spot a piece of old technology[.]

I think Spicer's diagnosis is broadly correct. But also that the sense of progress and change that Spicer was looking to itself emerged from the confluence of social and technological changes that 'only' a handful of generations of humans experienced, and that was highly anomalous in the long stretches of human existence. 


## BMB, EMB, AMB

To simplify to the point of abject caricature, let's divide the nature of cultural experience into three very loose epochs: 

1. Before the epoch of mass broadcast;
2. The epoch of mass broadcast;
3. After the epoch of mass broadcast. 

What do I mean by mass broadcast? Simply a series of widely used and adopted technologies that *transmit* the same engaging messages, through the same engaging media, via a small and finite number of channels, to a large and geographically disparate number of individuals. As with most attempts to represent the continuous as discrete, mass broadcast was a process, not an event. 

## The Centuries that Time Forgot

Let's say, however, that before there was mass broadcast, there was *geographic cultural heterogeneity*, as well as that the geographical contours within which humans found themselves had a profound effect on how much cultural variation exists across space, and where these cultures change. Two persons living half a mile away are likely to share much of the same culture if they are separated only by easily traversable plains or steppe, but could be profounding different - even speaking mutually indescipherable languages - if they are separated by large bodies of water or earth. The less easily traversable a terrain - think thick forest compared with open plains - the faster the culture changes between places a fixed distance apart. A clue to the reason for this is contained in the tendency for people, still, to describe distance in terms of time: **how far?** *20 minutes*. **How far?** *We can get there in a day but we'd have to rise early; probably better to stay overnight*. 

Which brings us to the surprisingly timeless concept of a *time budget*, meaning the amount of time each day (or each week, or month, or season or year), people will be willing to *spend* on different kinds of activities, including that of travelling. In general most people won't tend to want to spend more than, at the limit, a couple of hours a day travelling from place to place, with the optimal daily time budget for transport likely being around fifteen to thirty minutes. So, most of the people people have known, for almost all of human history and pre-history, have been within around half an hour of where they live. And before there was mass broadcast, this half hour radius likely largely determined *one's culture*. With walking speed around 5 km per hour, this implies that most people's culture, for most of the time that people have existed, was likely largely within a 2-3km radius. With the domestication of the horse, which could perhaps comfortably travel at 30 km per hour, this potential radius of common cultural influence likely expanded to around a 15 km radius (though only amongst those elites able to afford a horse), perhaps an eight-fold increase. And with a steam-powered train, a half-hour away could be perhaps 40km away, a both faster and more affordable two-and-a-bit-fold increase in the range of cultural exchange over the horse. 

## Mass Broadcast 

Each of these transportation technologies allowed for the geographic range of *two-way* cultural exchange to increase. But by *mass broadcast* I mean *one-way* cultural transmission instead. The messenger on horseback and the Town Cryer, the telegraph, the newspaper (in literate populations), the radio: all examples of mass broadcast. Suddenly *the few* could communicate to *the many*, and through this *some small but growing aspect* of the cultural experiences of *the many* came to become more similar. As a result of these technologies, people came to think of themselves as - amongst other things - part of the same nation: to be British or Scottish or Irish or French, rather than just as thatchers or coopers or people who live near that hill near that stream. 

And as *mass broadcast* technologies improved, so the cultural sway they had on ever more people increased. With moving images, people came to see people who they were told were or were not like them doing things they could imagine themselves doing, such as fighting in wars overseas. People separated by hundreds or thousands of miles came to see the same stories on screen, and so to become ever more wedded and united by ever more common cultural experiences. People heard themselves referred to on the wireless as a single people, and to think of themselves as such. 

## Culture and Technological Progress

But then technology begot technology, and prosperity begot prosperity, and change begot change, and so, much as people became used to thinking of themselves as a single nation, they also came to identify differentiation along generational lines: the world as older generations knew was no longer the world as younger generations were coming to understand. The norms were changing, the expectations were changing, the rules were changing. And so, as each generation entered adulthood, they came to realise that if they learned from their elders how to live in the world their elders lived in, they would be poorly equipped to live in the world as it would be for them. So, each new burgeoning adult generation sought to replace *vertical cultural transmission* (from the old-to-young) with *horizontal cultural transmission* (from peer-to-peer). 

With this switch from *vertical cultural transmission*, based on local extra-familial networks, to *horizontal cultural transmission*, what many of us now think of Culture (big C) began. Each generation had its own Culture: its own way of dressing, its own way of speaking, its own set of rules and expectations. Each new generations sought, through the missives of mass media, to learn what it meant to be *a child of the 1950s* or of *the 1960s*, or *the 1970s*, or *the 1980s*, or *the 1990s*. 

And it was these broadcast and telegraphed sempahores of cultural distinction - the changing hairstyles or hemlengths, or musical tastes -  of successive cohorts of persons born over the 20th century, that - I think - people like Michael Spicer (and by instinct, myself) are looking for, and failing to find, when making the declaration that *there has been no (cultural) progress since 1999*. What someone of my age, or Spicer's age, or almost any older living age, are looking for are signifiers that *the 2000s were about X*, *the 2010s were about Y*, and *the 2020s look to be about Z*. 

- The 1950s were about rockabilly and teddy boys
- The 1960s were about peace and love and rebellion and counterculture and hippies
- The 1970s were about anger and prog rock and punks
- The 1980s were about electropop and yuppies and performative androgyny
- The 1990s were about grunge and Britpop and new lads and ladettes 
- The 2000s were about raunchy pop singers and corporate malaise, and then about 9/11
- The 2010s were about ????
- The 2020s are about ????

In this sense, the *nothing has changed culturally* argument comes from a much lower ability to effectively stereotype young adults than was the case for about 50 years previously. But this inability to settle on a stereotype itself comes from a *much lower level of intra-generational cultural homogeneity* amongst youth generations of the last 20-25 years, whereas the *desire to stereotype* in this way comes from norms and expectations that persons born between around (say) 1940 and 1990 would have found easy to believe, but were likely not default expectations amongst older generations, and are likely also not default expectations amongst newer generations. 

Why? Because the epoch of mass broadcast is *over*. 

## What Now?

What's it been replaced with? **Algorithmic cultural segmentation**. 

i.e., as described by Spicer, the ever more precise segmentation of pseudo-personalised content into disparate and algorithmically determined customer groupings. *If you bought X, you're more likely to buy Y*. *If you watch X, you're likely to watch Y*. There is no Culture; there are *cultures*. The cultural homogeneity of the epoch of mass broadcast has been replaced by cultural heterogenity. But whereas previously geography was the prime determinant of this heterogeneity, now the prime determinant is the algorithmic cluster to which individuals have been assigned based on their observed preferences for different types of content. This means, on the one hand, that two people separated by hundreds of miles can be of the same culture, but on the other hand that two people living in neighbouring houses, or even in the same household, can potentially be of very different cultures, potentially so different as to be almost mutually intelligible. 

## Girls and Boys: Parallel Cultures

One tell of this kind of algorithmic cultural fissuring is in the increasing divide in political and social views amongst boys and girls at school, and young men and young women after compulsory education has ended. According to [this article](https://www.brookings.edu/articles/the-growing-gender-gap-among-young-people/), for instance, sex differences in political and social attitudes are greater for Generation Z than all previous generations. According to [this article](https://www.theguardian.com/us-news/ng-interactive/2024/aug/07/gen-z-voters-political-ideology-gender-gap), the sex gap in political preferences (Democrat or Republican, in the US context) roughly doubled between 2000 and 2024, due more to changes in young women's than young men's shift in preference. The relationship between sex and the type of social media boys and girls, and young men and women, have consumed since around 2008 have also been argued to explain trends in [mental health](https://www.amazon.co.uk/Anxious-Generation-Rewiring-Childhood-Epidemic-ebook/dp/B0CGWS3JQ6) and, even more controversially, [gender identity](https://en.wikipedia.org/wiki/Irreversible_Damage).

But if culture is now determined primarily through algorithmic segmentation then even accommodating and acknowledging growing within-generation sex differences may not do justice to the extent of cultural heterogeneity that exists within previously identified sociodemographic segments. Hence, again, the difficulty older generations (including my own) have with identifying broad characteristics and trends within the last fifteen so years as were apparent in previous decades. To the extent there is some agreement on a stereotype as applied by the old to the young, it's that contemporary younger generations are somewhat more cautious, more anxious, more attuned to injustice and offence, and so more censorious than previous generations at the same age. But as discussed this 'snowflake' characterisation seems partial at best, and to the extent it applies at all, seems to applies much more to girls and women than boys and men. Again, this stereotype perhaps reflects more a desire amongst older generations to apply a mass broadcast framework for thinking about culture in a post mass broadcast epoch. 

## My Segment?

To take my own reflected algorithmic segment on Youtube as an example. Currently it appears a strange mix of the following: sociopolitical video essays; long form interviews; videos on cookery and especially pizza making techniques; playthroughs and retrospectives on games from the 1980s and 1990s; and morbidly fascinating videos of Americans shooting things in slow motion with weaponry of various calibres. What culture, if any, does this weird admixture of video recommendations place me in? I'm really not sure, though think it vanishingly unlikely that anything as hyperspecialised would have become been programmed for the masses on the BBC, ITV, or even Channel 4. 


## Generation Zimmer 

And what, now, does terrestrial television largely comprise of? An increasing share of programming on the above channels seems to be based around feeding the nostalgic instincts of the mass broadcast generations. Recently, for example, I chanced upon an interview between Alan Titchmarsh (prominent in the 1990s) and Moira Stuart (prominent in the 1980s) where they shared fond reminiscences about working with Ronnie Corbet (prominent in the 1970s); [other guests on the same show](https://www.itv.com/watch/love-your-weekend-with-alan-titchmarsh/10a0437/10a0437a0154) included Anita Dobson (most prominent in the 1980s) and Ben Miller (a relative newcomer, whose programmes were first televised in the early 2000s). 

The draw of cosy nostalgia even pervades those channels that previously positioned themselves as edgy or countercultural: Back in late 2000 I remember watching *Have I Got News For You* (still being shown, with two of the same panellists), where a joke made at the time - in reference to the weeks-long litigation about the US presidential results - was that "news is currently just Bush and Gore... much like Channel 5". The joke was in reference to the then new terrestrial channel, which in a bid to attract viewers did, indeed, have a post watershed schedule almost entirely comprised of documentaries about sex workers and serial killers. Look to same timeslots now, however, and you're more likely to see documentaries about... the 1960s, 1970s and 1980s, featuring very familiar talking heads from the periods being reminisced about. Even Channel 4, which has a legal remit to provide an Alternative offering, increasingly comprises shows (like Countdown) that have run continuously for decades, and other cosy offerings in which well known and long established celebrities go for walks, take trains, or travel by narrowboat slowly across the British Isles, reminiscing fondly about their salad days from decades gone by. 

Both the cause and consequence of terrestrial television's steady descent into cosy nostalgia is that, by viewer demographics, it's both *old* and *ageing quickly*. By old I mean the average age of viewers is considerably older than the UK median age, 61 years of age for the BBC based on [this 2017 report](https://community.sony.co.uk/t5/the-lounge-room/average-age-of-bbc1-viewers-is-now-61/td-p/2313835), and so likely older still now. And by ageing quickly I mean that, although the average age of the UK population is itself ageing, it's likely the demographics of terrestrial television are ageing faster still. Although persons only have one alternative to ageing one year per year, populations *can* age faster or slower than this rate: London, for example, has long had a near static average age over time, because so many people migrate to the region in their late teens or early twenties, then from the region once they get to their twenties and thirties. By contrast certain regions in Northern England age much faster than one year per year, or the UK average rate of population ageing, because young adults tend to move elsewhere (such as to London). The broad magisteria of live TV viewership can also be thought of as a population, with 'tuning in' and 'switching off' (both archaic terms) somewhat like in- and out-migration, and the effects of these patterns of in-flow and out-flow largely causing this rapid ageing. 

And of course, not all people of the same age will have the same preferences, abilities with, or appetite for new technology and new developments. The forty-somethings, fifty-somethings and sixty-somethings who leave broadcast television will likely be those more technologically savvy than those they leave behind in front of the television. And so, the persons still watching - or primarily watching - live broadcast television will not only be *old* in chronological terms, but also *old at heart* in terms of their relative preferences for the old over the new. 

## Conclusion (Sort of)

All of which, in a very roundabout way, hopefully explains why the BBC still cares to tell its viewers, readers and listeners that there is a Christmas Number One (because it used to be a Big Deal last millennium), and also why this Christmas Number One is forty years old, and doing battle with songs that are just about of pensionable age. 
