---
title: "The Game of Life Beyond"
subtitle: "On the Psychological Mechanics of Cultist Simualtor"
author: "Jon Minton"
date: "2024-06-17"
categories: [psychology, games, fantasy]
---

## Warning/Preamble

*This post contains mild-to-moderate spoilers for the game [Cultist Simulator](https://en.wikipedia.org/wiki/Cultist_Simulator), which is available on [Steam](https://store.steampowered.com/app/718670/Cultist_Simulator/), [Switch](https://www.nintendo.com/en-gb/Games/Nintendo-Switch-download-software/Cultist-Simulator-Initiate-Edition-1904068.html), and likely other platforms besides. If you want to experience Cultist Simulator without these spoilers, please buy the game, play it for between ten and twenty hours, then return to this post. If you've already played it, have no interest in playing it, or aren't particularly bothered by spoilers, then please read on...*

## Introduction


The first time I became aware of Cultist Simulator was through a Youtube video. And when I first saw it, I thought it was either a joke, or at most highly unfinished. But I was wrong. 

Cultist Simulator has no tutorial, a big virtual table (sitting atop ethereal nothingness), many cards, and some counters (that 'accept' cards). Superficially, there's nothing else to it. Everything in the game happens on the table, and involves cards and counters. You can't get up, you don't see anyone, there's no dialogue, no cut-scenes or grand cinematics, and in a sense nothing to do except move cards and counters around on a board. 

But within this highly limited player canvas, Cultist Simulator is an incredible game, narratively rich, mechanically complex, hypnotic, engaging, brutal, cruel, relaxing, philosophical, psychological, literary, purposeful and intelligent. The simplicity and limitations in the ways that the player can interact with the game, and the game can feed back to the player, belie the underlying complexity and richness of the game's storytelling and mechanics. 

So, what is Cultist Simulator? Here's three answers: 

1. HP Lovecraft Solitaire
2. A rogue-like indie game
3. A human purpose and motivation simulator

In this post, I'm going to focus on the third of these three answers. Through the medium of virtual cards, and virtual counters, on a virtual board, Cultist Simulator offers a simplified and stylised representation of *real* human psychological and physiological needs. So, even if you have no interest in games, this aspect of this game might still be of interest to you. 

## Starting off

When you first start [^1] Cultist Simulator you have one card, and one counter. The card says **menial employment**, and the counter, which is larger than the card, says **work**. If you move the counter onto the card, nothing happens. But if you move the card onto the counter, a dialogue box opens showing the card - **menial employment** - embedded in the activity of **work**, the counter. You then have the option to undo this association, by moving the card out of the counter dialogue box, or to **commit** this action: *do* **work** with **menial employment**. 

[^1]: In Cultist Simulator, the previous game endings affect how the next game starts, in particular the role you are initially assigned. The very first role is known as The Aspirant, and this is what I'm describing here. 

So, you learn that, broadly speaking **the counters are verbs (or actions)** whereas **the cards are nouns (or things)**. 

Next, you learn that *actions take time*. Once you execute work with menial employment, a timer appears on the work counter, counting down to new events. You learn your job is a hospital porter, it pays poorly, brings you into contact with sickness and death, and that it's precarious. 

Very precarious: as then you're made redundant. As part of your redundancy package you receive some new cards, and some new counters: 

- cards: 
	- a bequest
	- reason
	- coins
- counters:
	- study

Before too long, you realise some of the cards relate to resources. These are: 

- coin
- reason
- passion
- health

And the range of counters (actions) available to you expands to: 

- work
- study
- dream
- explore
- talk

The human purpose and motivation simulation component of the game comes from a) realising that the four card resources above are aspects of the self that need to be effectively managed to survive; and b) realising that your own mind and body plays actions (generates counters) against you. You are, in this game, in a sense completing against yourself! 

## Early endings 


What does this mean in practice? Let's consider some in-game scenarios. 

- **Scenario 1**: After having been made redundant, you use your **reason** to seek employment, and find **clerical work** (under the critical and watchful gaze of Mr Glover Sr., the proprietor). You keep going to work, using - but never testing or developing - your **reason** to work to the required standards. This gives you enough **money** to fend off starvation, and a little more to pursue a sideline in occult literature. However, as you repeat the same quotidian cycle - sleep, work, sleep, work - you develop a sense of **restlessness**, of wanting or striving to do... *something* that's not what you're doing. You try to ignore this sense of **restlessness**, keep with the routine and ritual criticism of Mr Glover, but then eventually this **restlessness** turns into **dread** - what if *this* is all I'll ever be? Most of the time, you are able to eventually shrug off this sense of **dread**, wait out for this feeling to dissipate. But - as the nights get ever longer - you become more receptive to dark thoughts, and this sense of **dread** starts to build up, until it overwhelms you. This accumulation of **dread** develops into an existential black hole of **despair** from which you are unable to recover, and your story ends. 
- **Scenario 2**: You use your **reason** to find **clerical work**, but are also willing to listen to your heart. When you encounter **restlessness**, you recognise that as a signal to break from your hum-drum routine. One day, instead of going to work in the office, you use your **passion** to work on your **restlessness**, and produce passionate but poorly disciplined artworks fuelled by this restless energy. The artworks have a striking immediacy, and novel, vibrant creativity expressed within them, and manage to achieve a market value that covers your basic subsistence needs. However, in the time taken to pursue this restless passion, your tardiness at work has been noticed. You have been fired. You have the option to use your **passion** to beg for your old job back, but are too prideful to do this. Instead you decide to become an artist full time. However, without training and discipline in the arts, and without that burning restlessness that fuelled that initial artwork, your outputs are now lacking in both restless energy and talent, so they go unsold. Although you get some psychological succour from the process of making art, they do not pay the bills, and so do not provide succour for the body as well as the soul. So, penniless, your body slowly succumbs to **starvation**, and you die. Your story is at an end. 
- **Scenario 3**: You vigilantly and diligently attend your reasonably paying (but belittling and soul destroying) clerical job, but seek pharmaceutical solutions to your spiritual yearnings. You let your **restlessness** go unanswered, until it transforms into **dread**. But in the darkest months, when you are most at most susceptible to totalising melancholia, you use some of your licit earnings to buy illicit pharmacopeia, and try to find chemical **contentment** with which you can battle your lingering sense of **dread**. Unfortunately, this 'solution' is both expensive and harmful: You use so much of your earnings to try to anaesthetise the dark clouds of your unfulfilled yearnings that you have little or no monies left to broaden your mind or meet basic needs; and eventually your dalliances with drugs bring sickness: a sickness that, without the **vitality** of a healthy body or even more **money** to pay for treatment, leads to your death. Your story is at an end. 
- **Scenario 4**: You decide that work for you should mean labour, physical labour. You rent your body, your skeleton and muscles, to the highest bidder, and become an unskilled manual labourer. Your work doesn't pay much, meaning you have little resource to pursue any additional hobbies and passions, but it's *honest* work, that just about pays the bills. Your body gets stronger, but your mind and soul remain undeveloped. Eventually, you have some bad fortune, and become injured at work. Unfortunately, with your injury you cannot work, and without savings you cannot acquire the medicines needed to bring you back to health. And once again, without being able to work, you cannot pay the bills, and eventually die of both decrepitude and starvation. Your story is at an end. 
- **Scenario 5**: You manage to juggle your time successfully between the clerical job that pays the bills, and developing your interests and and understanding of hidden worlds and realities. You become a frequent visitor to Morland's, a bookseller specialising in esoterica. Your shelves groan with arcane knowledge and speculation, in particular about a hidden world called the Mansus, a reality beyond our reality accessible only through dreams and incantations. Your habit in bibliography becomes as expensive to maintain as your chemically-dependent cousin's was on that past journey. Superficially, at least, it appears less harmful. With your new-found enthusiasm for the arcane and esoteric, you can't help but discuss your interests with others; your colleagues at work start to find you strange and odd, but at least you're reliable, and seem oddly well connected to management, so they tolerate your eccentricities. You also meet likeminded journey-men and -women, who share many of your exotic interests. Along the way, you also attract the 'wrong kind of attention', from the 'authorities', who look at your interests with suspicion and concern. However, though they find your interests strange, they never manage to prove that your interests are illegal or dangerous. So, once again you seem to be safe, pursuing this double life of bookkeeping and occultism. Unfortunately, you start to find the contours of the Mansus, sketched piecemeal and imperfectly from your growing collection, *too* interesting, *too* seductive. Eventually, your **fascination** with the Mansus becomes all-consuming, this world of dreams more real, more purposive, more meaningful, than this fiction the unenlightened masses believe to be the 'real world'. You become unable to think about anything else, and so unable to function. You are insane, driven mad by your own passions. Your story is at an end. 

Each of the above represents a way the game can end early, due to a psychological or physiological challenge being made to you at certain points (or seasons) in the game, which you then fail to manage to meet. Without being attended to, each of these challenges will lead to a premature demise. And the way each challenge is overcome is by finding cards that function as *antidotes* to the psychological or physiological *poisons* that are the at heart of each challenge. 

## The Challenges of the Seasons

Let's look, in particular, at the two seasons that relate most strongly to psychological wellbeing: 

| Season                                    | Challenge                            | Poison          | Antidote                              |
| ----------------------------------------- | ------------------------------------ | --------------- | ------------------------------------- |
| Season of Despair: Bleak Thoughts         | Avoid Accumulating Three Dread       | **Dread**       | **Contentment**                       |
| Season of Visions: A Trembling in the air | Avoid Accumulating Three Fascination | **Fascination** | **Dread** or **Fleeting Reminiscence** [^2] |

[^2]: Fleeting Reminiscence is a card that can be obtained by using your Health to Explore. In effect it is the result of attempting to become a *flaneur*, mindfully observing the world as it really is, rather than as you dream it to be. However this same action can (I believe) also generate cards with opposing effects, which degenerate into Fascination. 

The first seasonal challenge is the challenge failed to reach scenario 1 above, whereas the second seasonal challenge is the challenge failed to reach scenario 5 above. Note the (anti)symmetry between the two seasons: **dread**, which is the *poison* in the contest of the **Season of Despair**, works as a potential *antidote* in the context of the **Season of Visions**. Put more simply, the psychological game mechanics seem to be suggesting: *too much dread weights you down so heavily you can no longer move, but some dread (or at least concern and anxiety about worldly things) can be what keeps you grounded and sane.* The complexity of this aspect of the game comes from this mechanic, the ways that thoughts and feelings that can be poisons in some contexts can be antidotes in other contexts, and the ways that trading off actions and rewards to balance these two central seasonal challenges leads to second order seasonal challenges that themselves need to be balanced: As mentioned, an 'easy' way to accumulate less dread and acquire more contentment is to become a full time artist, but in doing so you struggle to pay the bills, and so have enough resource to feed the body (Scenario 2); and an 'easy' way acquire contentment to combat the dread that accumulates from not pursuing your passions is through illicit pharmacopeia (dreaming on a 'tincture of opium'), but this route is both expensive and harmful to your body (Scenario 3). 

## Cultist Simulator as 'heightened' psychological realism?

The two seasonal challenges - of the **Season of Despair**, and the **Season of Visions** - appear an effective way to use game mechanics to represent - in a stylised, simplified, ideal typologised way - the dual psychological maladies of, respectively, **depression** and **mania**. For individuals diagnosed with Bipolar Disorder, there is a clear need to seek and maintain an even keel between these two psychological poles: an individual experiencing mania does not (so far as I understand it) simultaneously experience depression; and while that same individual is experiencing depression, they are not simultaneously experiencing mania. Both depression and mania can be thought of as maladies of excess, but of qualitatively different, and in some senses opposing, types of excess. 

As human psychology exists on a continuum, however, it is worth considering and contemplating the ways that this core psychological dilemma - the need to balance 'low' and 'high' moods - is something that just about everyone experiences to some varying extent, even though for most people this extent does not meet any clinical diagnostic thresholds. We forever need to make some effort to keep ourselves either from doing the psychological equivalent both of crashing into the ground, or soaring too high and burning up in the outer atmosphere. 

## Settling as an 'anti-Victory'

But if the psychological mechanics of Cultist Simulator evoke a quality of constantly trying to maintain an appropriate affective altitude while flying the vehicle of our own minds, the question this metaphor raises is: "What is our destination?" In Cultist Simulator, if we manage to successfully avoid the premature endings outlines in the five scenarios above, there are a number of destinations we can reach, and that lead to 'true' (rather than premature) game ending. And these 'true endings' are themselves categorised into 'Anti-Victories' and 'Victories'.

The Anti-Victories you can reach depend on the sort of character you start with. For the basic character, known as The Aspirant, the path of this Anti-Victory is broadly as follows:

- You diligently attend your office job at Glover & Glover; day after day, week after week. Your attendance remains broadly punctual, and you exhaust your Reason each day to ensure you meet the exacting standards of Glover Sr. Through your diligence, punctuality and hard work, you manage to receive promotions at work, and with this greater financial security and reduced scrutiny. The job becomes less unpleasant, as well as better paid. One day, you are given the chance to offer not just your Reason to your job, but also to give your Passion to the role. On doing so, you come to identify not just your body and your mind with the job, but also your soul. You have stopped struggling, stopped striving or believing that you are or are meant to be something other than someone who works in an office and completes paperwork. You have achieved a form of peace, and a kind of purpose, amid the forms and filing cabinets. You quietly put away your foolish, childish hopes and dreams - of being something more, of finding something grander or more meaningful in the world. Your job is now your vocation. Your story is at an end. 

For other character types, there are equivalent Anti-Victories, each based around the primary occupational role you were first encouraged to fulfil: as a Detective, you can successfully lock up undesirables, rather than attempting to understand, explore, and risk becoming seduced by the ideologies that drive them; and as a Dancer, you can use your physical prowess not to seek cosmic connection with the world of dreams, but to seduce a rich (but dull) suitor whom you agree to marry. In each case, you have managed to been successful in staying on the main road you started on, but been unsuccessful in not turning onto routes less travelled.  

## Conclusion

So, despite its apparent simplicity, Cultist Simulator is - in addition to being beautifully designed and well written - a stylised human psychology and purpose simulator, with complex game mechanics for trying to represent the need to handle the ups-and-downs of the everyday, but also the need to strive for purpose and meaning beyond the merely functional and conventional, and that bring you closer to your dreams. 

Of course, Cultist Simulator is *fantasy*, and the particular courses offered in the game as to how to achieve 'true' endings that are not Anti-Victories are not available to us in real life. But the psychological and physiological dilemmas and challenges presented to the player in Cultist Simulator appear to represent *real* (albeit simplified and stylised) dilemmas and challenges that every one of us, to varying extents, will have encountered, be encountering, and forever be attempting to navigate as best we can. 

As mentioned near the start, Cultist Simulator does not have a tutorial. And neither does life. 