<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jon Minton">
<meta name="dcterms.date" content="2024-10-19">

<title>Jon Minton’s Blog - Demystifying and Disenchanting Statistical Significance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<script src="../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../../styles.css">
<meta name="twitter:title" content="Jon Minton’s Blog - Demystifying and Disenchanting Statistical Significance">
<meta name="twitter:description" content="Reframing t tests as cheap data budgeting advice">
<meta name="twitter:site" content="@jonminton">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title">Jon Minton’s Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-statistics--data-science" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Statistics &amp; Data Science</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-statistics--data-science">    
        <li>
    <a class="dropdown-item" href="../../../../glms.html" rel="" target="">
 <span class="dropdown-text">Statistical Theory and Applications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../tardy-tuesday.html" rel="" target="">
 <span class="dropdown-text">Tardy Tuesday</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../hand-drawn-statistics.html" rel="" target="">
 <span class="dropdown-text">Hand-drawn Statistics</span></a>
  </li>  
        <li class="dropdown-header">Total words: 182284</li>
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../unpop.html" rel="" target="">
 <span class="menu-text">Unpop</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://jonminton.net" rel="" target=""><i class="bi bi-window-fullscreen" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JonMinton" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/JonMinton" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://uk.linkedin.com/in/jon-minton-09480b13a" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../../index.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Demystifying and Disenchanting Statistical Significance</h1>
            <p class="subtitle lead">Reframing t tests as cheap data budgeting advice</p>
                                <div class="quarto-categories">
                <div class="quarto-category">statistics</div>
                <div class="quarto-category">hypothesis testing</div>
                <div class="quarto-category">p values</div>
                <div class="quarto-category">t tests</div>
                <div class="quarto-category">f tests</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Jon Minton </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 19, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>In the long series of statistical posts I’ve produced so far, one thing I’ve not discussed much is <strong>hypothesis testing</strong>, the concept of <strong>statistical significance</strong>, and the related concept of the <strong>P value</strong>. If you’re familiar with how statistics is often used and reported within many academic fields, this lack of focus on statistical significance may appear an oversight. Indeed, in my new role as a statistician working with clinical trials data, they’re essential, arguably the main purpose of going to the great expense and effort involved in conducting the trials.</p>
<p>In the posts so far, the idea of hypothesis testing has perhaps been most salient within the series on <a href="../../../../posts/glms/hacker-stats/bootstrapping/index.html">bootstrapping</a> and <a href="../../../../posts/glms/hacker-stats/resampling-approaches-intro/index.html">resampling methods</a>. Here we discussed the idea that, if we compare a <strong>summary statistic</strong> observed in our data, with a <strong>distribution of that same summary statistic that we would expect to see if there were no real relationship</strong> between two or more variables, then we can get an estimate of how probable it would be to see a summary statistic as extreme or more extreme than the value we did observe in the real data, if there really were no real relationship between the variables of interest.</p>
<p>Whether using resampling and bootstrapping methods, or more conventional methods, the underyling aim and approach in hypothesis testing is the same. There are always the same elements in play, even if the approaches used to derive, estimate or represent some of these elements differ between methods. These elements comprise:</p>
<ul>
<li><strong>Observation</strong>: An observed summary statistic;</li>
<li><strong>Null Distribution</strong>: A distribution of hypothetical observed summary statistics which would be expected under the Null Hypothesis</li>
<li><strong>Decision Rule</strong>: A pre-established rule for comparing the <strong>Observation</strong> against <strong>Null Distribution</strong>, from which we make one of two binary declarations:
<ul>
<li>That we <em>reject</em> the Null Hypothesis;</li>
<li>That we <em>fail to reject</em> the Null Hypothesis.</li>
</ul></li>
</ul>
</section>
<section id="aim" class="level2">
<h2 class="anchored" data-anchor-id="aim">Aim</h2>
<p>The aim of this post is to reintroduce, <em>demystify</em> and <em>disenchant</em> the contents of statistical model summaries of the type that show P values and stars against different coefficients in a model. My underlying argument is these tables are often grossly overinterpreted, especially by many academic and clinical practitioners, as answering hypotheses we’re actually interested in having answered. Once we understand what they contain, and can make them ourselves, we can instead have a more realistic interpretation of the kinds of information they contain, and what we should use them for. The specific role of such tables, I argue, is mainly to provide some ‘quick-and-dirty’ information about whether we should look at simplifying the model we’re using to represent the data, and not necessarily to dispositively ‘prove’ or ‘disprove’ that one factor of substantive interest substantively influences another factor of substantive interest. All too often, statistical model summary tables are treated as the last stage of a piece of analysis, when instead I suggest they should really be considered one of the first stages.</p>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting started</h2>
<p>Let’s get started by running a regression equation on a very well known dataset :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa</code></pre>
</div>
</div>
<p>Let’s say we want to create a linear regression model to predict <code>Petal.Length</code> based on all other available variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mod_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>   Petal.Length <span class="sc">~</span> Petal.Width <span class="sc">+</span> Sepal.Length <span class="sc">+</span> Sepal.Width <span class="sc">+</span> Species, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> iris</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-r-linear-regression-summary-table" class="level2">
<h2 class="anchored" data-anchor-id="the-r-linear-regression-summary-table">The R Linear Regression Summary Table</h2>
<p>The standard summary output for this model is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width + 
    Species, data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.78396 -0.15708  0.00193  0.14730  0.65418 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -1.11099    0.26987  -4.117 6.45e-05 ***
Petal.Width        0.60222    0.12144   4.959 1.97e-06 ***
Sepal.Length       0.60801    0.05024  12.101  &lt; 2e-16 ***
Sepal.Width       -0.18052    0.08036  -2.246   0.0262 *  
Speciesversicolor  1.46337    0.17345   8.437 3.14e-14 ***
Speciesvirginica   1.97422    0.24480   8.065 2.60e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2627 on 144 degrees of freedom
Multiple R-squared:  0.9786,    Adjusted R-squared:  0.9778 
F-statistic:  1317 on 5 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The Coefficients section of the summary contains the following columns:</p>
<ul>
<li>Name of coefficient (implicitly)</li>
<li>Estimate</li>
<li>Std. Error</li>
<li>t value</li>
<li>Pr(&gt;|t|)</li>
<li>Number of stars (implicitly)</li>
</ul>
<section id="cultish-conventions-to-avoid-and-deprogram-yourself-of" class="level3">
<h3 class="anchored" data-anchor-id="cultish-conventions-to-avoid-and-deprogram-yourself-of">Cultish Conventions to avoid and deprogram yourself of</h3>
<p>If you’ve been taught to (mis)use statistics in the standard way, you might be drawn to the right-most column: Number of stars, and to looking for those rows with at least two stars. You’ll notice that the smaller the value in the column to its left, <code>Pr(&gt;|z|)</code>, which is the P value, the more stars there tend to be. In this case the row for the coefficient <code>Sepal.Width</code> has the largest P value, and so just has a single star next to it; all the other coefficients have much smaller P values, and all have three stars next to them.</p>
<p>The standard misuse of statistics in many academic fields encourages a fixation with the number of stars next to tables of coefficients like the one above, and in particular to looking for at least as many stars as correspond to a P value of 0.05 or lower (one star or more, in this case). This learned pathology is known as ‘star gazing’, and the fixation on finding stars on coefficients which correspond to P values of less than 0.05 has been termed <strong>the sizeless stare</strong> in the book <em>The Cult of Statistical Significance</em> <span class="citation" data-cites="mccloskey_cult_2008">(<a href="#ref-mccloskey_cult_2008" role="doc-biblioref">McCloskey and Ziliak 2008</a>)</span>. The rule of thumb, which all too often becomes a <em>de facto</em> rule of academic (and clinical) life, is that if the P value is less than 0.05 then its effects on the outcome being modelled have been shown to be ‘statistically significant’ - meaning it merits publication and promotion, and the research has been a ‘success’ - and if it is above 0.05 then it is not ‘statistically significant’ - meaning it does not merit publication and promotion, and the research has been a ‘failure’.</p>
<p>But what do the coefficients, the t values, the P values, and the stars, <em>actually</em> mean? Where do they come from? How does they relate to hypothesis testing, with its decision rules, null distributions and P values? Which hypotheses are being tested? Are they hypotheses actually worth testing?</p>
</section>
</section>
<section id="reframing-statistical-models" class="level2">
<h2 class="anchored" data-anchor-id="reframing-statistical-models">Reframing statistical models</h2>
<p>To start to answer these questions, it is worth taking a few steps back, and entertaining the following propositions :</p>
<blockquote class="blockquote">
<ol type="1">
<li>A statistical model is a data reduction tool;</li>
<li>The number of observations in our dataset is a fixed budget we can choose to spend in different ways through different statistical model specifications.</li>
</ol>
</blockquote>
<p>What do I mean by this? Well, say the dataset contains 100 observations. This is our data budget, that we spend whenever we fit a model based on the dataset. And say our statistical model contains five coefficients. What this means is that we are trying to represent - in a simplified and stylised way - the kinds of relationships observed between variables in our data through a much smaller number of coefficients than we had observations in our data. We are trying to <em>give the gist</em> of what we’re seeing in our data, which required 100 observations to express, through a model that only takes five coefficients to express. The model, therefore, is a representation of the data that’s only one-twentieth (i.e.&nbsp;100 divided by five) as big. This is what I mean by proposition 1), <em>A statistical model is a data reduction tool</em>. If we were to save the model, it would take less space on our hard drive than the data from which it’s derived; if we were to send the model, it would take less time to send than our data.</p>
<p>And what do I mean by fixed data budget? Well, if we are going to try and represent a lot of observations with a small number of model coefficients, it’s important to use as much information as is available to us from the dataset to make select the best possible coefficients. We could try to represent our 100 observation dataset through a model with four coefficients, or five coefficients, or six coefficients, for example. Of these three model specifications, the four coefficient model is the simplest, and the six coefficient model is the most complicated. But for all three model specifications the data budget available to calibrate it is the same: 100 observations. So, if using the five or six coefficient models, our fixed data budget has to be stretched a bit further compared with the simplest, four coefficient model.</p>
</section>
<section id="data-budgets-and-how-to-spend-them" class="level2">
<h2 class="anchored" data-anchor-id="data-budgets-and-how-to-spend-them">Data Budgets and how to spend them</h2>
<p>So, what is the data budget, and what’s the number of coefficients, in our dataset and model respectively? First the data budget:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 150</code></pre>
</div>
</div>
<p>150 observations. That’s the budget we’re spending to produce our model.</p>
<p>Now what’s the number of coefficients of our model?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">coefficients</span>(mod_full))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<p>Six coefficients. If we take a ratio of the number of observations (our data budget) to the number of model coefficients, i.e.&nbsp;divide 150 by six, we end up with a factor of 25. We could call this quantity something like our ‘compression ratio’ from going from the data to our representation of the data (i.e.&nbsp;the model).</p>
<p>However a more common metric to see is the difference between our data budget and our number of model coefficients, i.e.&nbsp;150 <em>minus</em> six rather than 150 divided by six. In this example <code>150 - 6 = 144</code>. This value, <code>144</code>, is reported somewhere in the model summary. Let’s look at it again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width + 
    Species, data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.78396 -0.15708  0.00193  0.14730  0.65418 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -1.11099    0.26987  -4.117 6.45e-05 ***
Petal.Width        0.60222    0.12144   4.959 1.97e-06 ***
Sepal.Length       0.60801    0.05024  12.101  &lt; 2e-16 ***
Sepal.Width       -0.18052    0.08036  -2.246   0.0262 *  
Speciesversicolor  1.46337    0.17345   8.437 3.14e-14 ***
Speciesvirginica   1.97422    0.24480   8.065 2.60e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2627 on 144 degrees of freedom
Multiple R-squared:  0.9786,    Adjusted R-squared:  0.9778 
F-statistic:  1317 on 5 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The number <code>144</code> is shown on the third line from the bottom, and the bottom line:</p>
<ul>
<li><code>144 degrees of freedom</code></li>
<li><code>144 DF</code></li>
</ul>
<p>So, we know from this that DF stands for <em>degrees of freedom</em>, and can maybe infer from this that, if this number is reported twice, it’s probably quite important.</p>
<p>What are degrees of freedom? Continuing the analogy of the number of observations being our ‘data budget’, we can think of the degrees of freedom as <em>the maximum amount of our remaining data budget we could spend on our model before going ‘bankrupt’</em>. What does ‘bankruptcy’ look like in modelling terms? Well, given a model is a data reduction tool, we obviously can’t have a model with more coefficients than there are observations in our dataset. This wouldn’t be data reduction; it would be data expansion: trying to get something from nothing.</p>
</section>
<section id="data-bankruptcy" class="level2">
<h2 class="anchored" data-anchor-id="data-bankruptcy">Data Bankruptcy</h2>
<p>Let’s explore this a bit further by looking at a slightly simpler model, but using much less data: We’ll fit four coefficients, but using only six, five, four or three observations from the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>iris_6 <span class="ot">&lt;-</span> iris[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(iris),<span class="dv">6</span>, <span class="at">replace=</span><span class="cn">FALSE</span>),]</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>iris_5 <span class="ot">&lt;-</span> iris[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(iris),<span class="dv">5</span>, <span class="at">replace=</span><span class="cn">FALSE</span>),]</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>iris_4 <span class="ot">&lt;-</span> iris[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(iris),<span class="dv">4</span>, <span class="at">replace=</span><span class="cn">FALSE</span>),]</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>iris_3 <span class="ot">&lt;-</span> iris[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(iris),<span class="dv">3</span>, <span class="at">replace=</span><span class="cn">FALSE</span>),]</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>mod_6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Petal.Width <span class="sc">+</span> Sepal.Length <span class="sc">+</span> Sepal.Width, <span class="at">data =</span> iris_6)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>mod_5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Petal.Width <span class="sc">+</span> Sepal.Length <span class="sc">+</span> Sepal.Width, <span class="at">data =</span> iris_5)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>mod_4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Petal.Width <span class="sc">+</span> Sepal.Length <span class="sc">+</span> Sepal.Width, <span class="at">data =</span> iris_4)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>mod_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Petal.Width <span class="sc">+</span> Sepal.Length <span class="sc">+</span> Sepal.Width, <span class="at">data =</span> iris_3)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width, 
    data = iris_6)

Residuals:
      34      144      113       37       60      118 
-0.08918 -0.27835 -0.19963 -0.02312  0.27089  0.31938 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)   -1.6225     1.4939  -1.086    0.391  
Petal.Width    2.1564     0.6215   3.470    0.074 .
Sepal.Length   0.3062     0.5510   0.556    0.634  
Sepal.Width    0.2372     0.6914   0.343    0.764  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3881 on 2 degrees of freedom
Multiple R-squared:  0.9889,    Adjusted R-squared:  0.9722 
F-statistic: 59.38 on 3 and 2 DF,  p-value: 0.01661</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width, 
    data = iris_5)

Residuals:
      140        62        85        93        39 
 0.026739 -0.063968  0.019746  0.006685  0.010799 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)    6.5524     0.8724   7.511   0.0843 .
Petal.Width    2.7874     0.1612  17.294   0.0368 *
Sepal.Length  -0.4326     0.1218  -3.552   0.1747  
Sepal.Width   -1.3058     0.2018  -6.470   0.0976 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0732 on 1 degrees of freedom
Multiple R-squared:  0.9994,    Adjusted R-squared:  0.9977 
F-statistic: 588.7 on 3 and 1 DF,  p-value: 0.03029</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width, 
    data = iris_4)

Residuals:
ALL 4 residuals are 0: no residual degrees of freedom!

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)      12.3        NaN     NaN      NaN
Petal.Width       1.5        NaN     NaN      NaN
Sepal.Length     -7.0        NaN     NaN      NaN
Sepal.Width       6.5        NaN     NaN      NaN

Residual standard error: NaN on 0 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:    NaN 
F-statistic:   NaN on 3 and 0 DF,  p-value: NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width, 
    data = iris_3)

Residuals:
ALL 3 residuals are 0: no residual degrees of freedom!

Coefficients: (1 not defined because of singularities)
             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   -3.0012        NaN     NaN      NaN
Petal.Width    2.4198        NaN     NaN      NaN
Sepal.Length   0.6914        NaN     NaN      NaN
Sepal.Width        NA         NA      NA       NA

Residual standard error: NaN on 0 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:    NaN 
F-statistic:   NaN on 2 and 0 DF,  p-value: NA</code></pre>
</div>
</div>
<ul>
<li>When there are six observations, the four coefficient model has two degrees of freedom.</li>
<li>When there are five observations, the four coefficient model has one degree of freedom.</li>
<li>When there are four observations, the four coefficient model has no degrees of freedom.</li>
<li>When there are three observations, the four coefficient model is converted into a three coefficient model (See the ‘NA’ value reported for the coefficient <code>Sepal.Width</code>) and has no degrees of freedom.</li>
</ul>
<p>So, it’s clear number of observations = number of model coefficients represents the hard limit on the level of complexity of a model that can be fit from a given dataset. To reiterate: a model cannot make something out of nothing.</p>
<p>And if we look at the coefficients themselves, we can see they seem quite ‘wild’: The coefficients for the intercept, for example, change from -1.6 to 6.6 to 12.3 to -3.0 with each reduction of just a single observation. This means that, ideally, the number of observations should be much greater than the number of coefficients, otherwise there’s not much information available to fit (choose the best value of) each coefficient well. When we have more information to go on, the model fit improves.</p>
</section>
<section id="getting-away-with-it" class="level2">
<h2 class="anchored" data-anchor-id="getting-away-with-it">Getting away with it</h2>
<p>Given more observations for each model coefficient tends to be better, we now have a third proposition:</p>
<blockquote class="blockquote">
<ol start="3" type="1">
<li>If we can get away with it, a simpler model is preferable to a more complicated model.</li>
</ol>
</blockquote>
<p>So, can we? Get away with it, I mean? What does ‘get away with it’ even mean?</p>
<p>To a large extent, the whole hypothesis testing framework 9as presented in standard statistical model summary tables0 can be thought of as a way of formalising this concept of ‘getting away with’ using a simpler model instead of a more complex model. When can we decide that the simpler model is <em>good enough</em>, and that we can use it instead of the more complex model, allowing us to spread our data budget a bit further?</p>
</section>
<section id="restrictions-and-nests" class="level2">
<h2 class="anchored" data-anchor-id="restrictions-and-nests">Restrictions and Nests</h2>
<p>Consider the following two model specifications:</p>
<ul>
<li><ol type="A">
<li><code>Y ~ 4 * intercept + 0.3 * thing_one + 0.0 * thing_two</code></li>
</ol></li>
<li><ol start="2" type="A">
<li><code>Y ~ 4 * intercept + 0.3 * thing_one</code></li>
</ol></li>
</ul>
<p>The numbers represent in the above represent the coefficients, which we can imagine stacking into a single vector object. For the first specification these are <span class="math inline">\(\beta = \{ 4, 0.3, 0 \}\)</span>, and for the second specification these are <span class="math inline">\(\beta = \{4, 0.3 \}\)</span>. It should be clear that in practice these two model specifications are really <em>exactly the same</em>: because the coefficient on <code>thing_two</code> is 0, the predicted value, <code>Y</code>, won’t change no matter how much the value of <code>thing_two</code> changes, because zero times anything is still zero.</p>
<p>Now consider this slight variation of the above:</p>
<ul>
<li><ol type="A">
<li><code>Y ~ around 4 * intercept + around 0.3 * thing_one + around 0.1 * thing_two</code></li>
</ol></li>
<li><ol start="2" type="A">
<li><code>Y ~ around 4 * intercept + around 0.3 * thing_one + exactly 0 * thing_two</code></li>
</ol></li>
</ul>
<p>Here I’m using the word ‘around’ to indicate that there’s uncertainty about the true value of the coefficients for the intercept, <code>thing_one</code> and <code>thing_two</code>. This uncertainty comes from having a finite number of observations from which to fit the coefficients in the model, i.e.&nbsp;a limited data budget to spend on calibrating our model’s coefficients. The same data budget could either: i) be used to fit <span class="math inline">\(k\)</span> parameters less precisely; or ii) <span class="math inline">\(k-1\)</span> parameters more precisely.</p>
</section>
<section id="statistical-tests-in-the-context-of-data-budgeting" class="level2">
<h2 class="anchored" data-anchor-id="statistical-tests-in-the-context-of-data-budgeting">Statistical Tests in the context of Data Budgeting</h2>
<p>The fundamental role of the standard hypothesis tests reported in a statistical model summary table is (or ought to be) to help us choose between these two model options: i) a more complicated model fit less precisely; or ii) a less complicated model fit more precisely. This trade-off exists, and always exists, because of the fixed data budget available to us.</p>
</section>
<section id="restricted-and-unrestricted-models" class="level2">
<h2 class="anchored" data-anchor-id="restricted-and-unrestricted-models">Restricted and Unrestricted Models</h2>
<p>Within the terminology of model testing and comparison, the model of specification A is referred to as the <strong>unrestricted model</strong>, and the model of specification B is referred to as the <strong>restricted model</strong>. Additionally, model B is said to be <strong>nested within</strong> model A. For model A, there are <em>three</em> parameters whose coefficient values are determined by the data: the data budget is spent three ways; for model B, there are <em>two</em> parameters whose coefficient values are determined by the data: the data budget is spent two ways. Model B is known as a <strong>restricted model</strong> because the coefficient on the third variable, <code>thing_two</code>, is not determined by (fitted using) the data, but instead <em>imposed</em> - forced to be zero - by who-ever or what-ever specified this model.</p>
<p>Note that, whenever we do not include a variable in a dataset in a model specification used to represent that dataset, we are automatically, implicitly, applying model restrictions and constraints of the form above: not including a term in a model is always equivalent to assuming the value of the model coefficient of that term is exactly zero. Because of this, we can almost always think of a given model as both a restricted version of a more complicated model, and as an unrestricted version of a less complicated model.</p>
</section>
<section id="t-scores-as-cheap-model-pruning-advice" class="level2">
<h2 class="anchored" data-anchor-id="t-scores-as-cheap-model-pruning-advice">T scores as cheap model pruning advice</h2>
<p>How does this line of argument relate to the kinds of hypothesis-test-based information commonly displayed as part of a statistical model summary? Well, <em>the P values reported for each coefficient in a model summary are in effect tests for a pairwise Null hypothesis that the true value of that coefficient is zero</em>. They are also approximately, but not exactly, equivalent to the comparing the model fit with a pairwise restricted version of the model in which the coefficient of interest is constrained to zero.</p>
</section>
<section id="rebuilding-statistical-model-summary-tables" class="level2">
<h2 class="anchored" data-anchor-id="rebuilding-statistical-model-summary-tables">Rebuilding statistical model summary tables</h2>
<p>Where does the information required to conduct these pairwise Null hypothesis tests come from? Let’s look again at the main model we fit and see if we can derive the summary table information ourselves:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width + 
    Species, data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.78396 -0.15708  0.00193  0.14730  0.65418 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -1.11099    0.26987  -4.117 6.45e-05 ***
Petal.Width        0.60222    0.12144   4.959 1.97e-06 ***
Sepal.Length       0.60801    0.05024  12.101  &lt; 2e-16 ***
Sepal.Width       -0.18052    0.08036  -2.246   0.0262 *  
Speciesversicolor  1.46337    0.17345   8.437 3.14e-14 ***
Speciesvirginica   1.97422    0.24480   8.065 2.60e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2627 on 144 degrees of freedom
Multiple R-squared:  0.9786,    Adjusted R-squared:  0.9778 
F-statistic:  1317 on 5 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The only information we actually need from the model are the values in the <code>Estimate</code> and <code>Std. Error</code> columns. As we’ll see, the values in the corresponding <code>t value</code> and <code>Pr(&gt;|t|)</code> columns are derived from these first two columns. (And the stars are derived from the <code>Pr(&gt;|t|)</code> column values.)</p>
<section id="finding-the-estimate" class="level3">
<h3 class="anchored" data-anchor-id="finding-the-estimate">Finding the estimate</h3>
<p>Firstly, we can get the value of the <code>Estimate</code> column by applying the <code>coefficients()</code> function to the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>our_estimates <span class="ot">&lt;-</span> <span class="fu">coefficients</span>(mod_full)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>our_estimates</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)       Petal.Width      Sepal.Length       Sepal.Width 
       -1.1109888         0.6022215         0.6080058        -0.1805236 
Speciesversicolor  Speciesvirginica 
        1.4633709         1.9742229 </code></pre>
</div>
</div>
<p>We can see that these values are identical to those in the <code>Estimate</code> column of summary.</p>
</section>
<section id="finding-the-standard-errors" class="level3">
<h3 class="anchored" data-anchor-id="finding-the-standard-errors">Finding the standard errors</h3>
<p>What about the contents of the standard error column? Getting this quantity is a bit more cryptic and involved. Firstly, we can use the function <code>vcov()</code> to get the variance-covariance matrix of the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>mod_full <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">vcov</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   (Intercept)   Petal.Width  Sepal.Length  Sepal.Width
(Intercept)        0.072831592  0.0128158873 -0.0063645539 -0.012468737
Petal.Width        0.012815887  0.0147483563 -0.0009380611 -0.003427085
Sepal.Length      -0.006364554 -0.0009380611  0.0025245414 -0.001762701
Sepal.Width       -0.012468737 -0.0034270855 -0.0017627006  0.006457374
Speciesversicolor -0.017507064 -0.0173108502 -0.0024945745  0.009589516
Speciesvirginica  -0.019784873 -0.0263239584 -0.0031243418  0.011820452
                  Speciesversicolor Speciesvirginica
(Intercept)            -0.017507064     -0.019784873
Petal.Width            -0.017310850     -0.026323958
Sepal.Length           -0.002494574     -0.003124342
Sepal.Width             0.009589516      0.011820452
Speciesversicolor       0.030086597      0.040493882
Speciesvirginica        0.040493882      0.059926863</code></pre>
</div>
</div>
<p>The on-diagonal terms (from the top left to the bottom right corners of the matrix) give the variance of given coefficients; i.e.&nbsp;the amount of uncertainty around the point estimates (the <code>Estimate</code> column of the model summary output; and the result of calling the <code>coefficients()</code> function on the model). Off-diagonal values in the matrix, by contrast, show the covariance between any two coefficients, i.e.&nbsp;a measure of the strength and direction of association between any two terms.</p>
<p>As we are only interested in the on-diagonal terms from this matrix, however, we can use the <code>diag()</code> function to extract them, turning the matrix we started with into a vector:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>mod_full <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">vcov</span>() <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">diag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)       Petal.Width      Sepal.Length       Sepal.Width 
      0.072831592       0.014748356       0.002524541       0.006457374 
Speciesversicolor  Speciesvirginica 
      0.030086597       0.059926863 </code></pre>
</div>
</div>
<p>This now returns only the covariances. The relationship between a covariance and a standard deviation is simple: a standard deviation is simply the square root of a covariance:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>our_ses <span class="ot">&lt;-</span> mod_full <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">vcov</span>() <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">diag</span>() <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">sqrt</span>()</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>our_ses</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)       Petal.Width      Sepal.Length       Sepal.Width 
       0.26987329        0.12144281        0.05024482        0.08035779 
Speciesversicolor  Speciesvirginica 
       0.17345489        0.24479964 </code></pre>
</div>
</div>
<p>Let’s now compare the estimates and standard errors we’ve extracted with those reported in the summary table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>our_summary_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">estimate =</span> our_estimates,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">std_err =</span> our_ses</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>our_summary_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    estimate    std_err
(Intercept)       -1.1109888 0.26987329
Petal.Width        0.6022215 0.12144281
Sepal.Length       0.6080058 0.05024482
Sepal.Width       -0.1805236 0.08035779
Speciesversicolor  1.4633709 0.17345489
Speciesvirginica   1.9742229 0.24479964</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width + 
    Species, data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.78396 -0.15708  0.00193  0.14730  0.65418 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -1.11099    0.26987  -4.117 6.45e-05 ***
Petal.Width        0.60222    0.12144   4.959 1.97e-06 ***
Sepal.Length       0.60801    0.05024  12.101  &lt; 2e-16 ***
Sepal.Width       -0.18052    0.08036  -2.246   0.0262 *  
Speciesversicolor  1.46337    0.17345   8.437 3.14e-14 ***
Speciesvirginica   1.97422    0.24480   8.065 2.60e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2627 on 144 degrees of freedom
Multiple R-squared:  0.9786,    Adjusted R-squared:  0.9778 
F-statistic:  1317 on 5 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Both the estimates and standard errors appear identical.</p>
</section>
<section id="calculating-the-t-values" class="level3">
<h3 class="anchored" data-anchor-id="calculating-the-t-values">Calculating the t values</h3>
<p>How do we then produce the t values shown in the summary tables? These are simply <em>the number (and direction) of standard errors</em> that the estimate value is away from the value of zero. We can produce this simply by dividing one number by the other:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>our_t_values <span class="ot">&lt;-</span> our_estimates <span class="sc">/</span> our_ses</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>our_summary_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">estimate =</span> our_estimates,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">std_err =</span> our_ses,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>   <span class="at">t_value =</span> our_t_values</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>our_summary_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    estimate    std_err   t_value
(Intercept)       -1.1109888 0.26987329 -4.116705
Petal.Width        0.6022215 0.12144281  4.958890
Sepal.Length       0.6080058 0.05024482 12.100867
Sepal.Width       -0.1805236 0.08035779 -2.246498
Speciesversicolor  1.4633709 0.17345489  8.436608
Speciesvirginica   1.9742229 0.24479964  8.064648</code></pre>
</div>
</div>
<p>Again, the t values we have calculated are identical to those reported in the summary.</p>
</section>
<section id="deriving-the-p-values" class="level3">
<h3 class="anchored" data-anchor-id="deriving-the-p-values">Deriving the p values</h3>
<p>Finally, how do we calculate the associated P value? This is the probability of a t distribution generating a t value as or more extreme as the t value we have observed for that coefficient. The t distribution requires two parameters: the t value itself, and the number of degrees of freedom, which as discussed previously is the difference between the number of observations in the dataset and the number of parameters in the model.</p>
<p>The default type of test reported in the summary table is a two-sided test, meaning t values much lower than zero, and t values much higher than zero, count equally as deviations potentially inconsistent with the implied Null hypothesis, that the true t value is really zero. Because of this, the P value involves doubling the complement of (1 minus) the cumulative probability probability of a t distribution up to and including the <em>absolute value</em> of the t statistic observed…</p>
<p>Got that? Don’t worry! The code required to do this is shown below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>n_obs <span class="ot">&lt;-</span> <span class="fu">nrow</span>(iris)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>n_coeff <span class="ot">&lt;-</span> <span class="fu">length</span>(our_estimates)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> n_obs <span class="sc">-</span> n_coeff</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Our magical formula for the P value below:</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>our_p_values <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fu">abs</span>(our_t_values), <span class="at">df =</span> df))</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>our_summary_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>   <span class="at">estimate =</span> our_estimates,</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>   <span class="at">std_err =</span> our_ses,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>   <span class="at">t_value =</span> our_t_values,</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>   <span class="at">p_value =</span> our_p_values</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>our_summary_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    estimate    std_err   t_value      p_value
(Intercept)       -1.1109888 0.26987329 -4.116705 6.445916e-05
Petal.Width        0.6022215 0.12144281  4.958890 1.968679e-06
Sepal.Length       0.6080058 0.05024482 12.100867 0.000000e+00
Sepal.Width       -0.1805236 0.08035779 -2.246498 2.619373e-02
Speciesversicolor  1.4633709 0.17345489  8.436608 3.153033e-14
Speciesvirginica   1.9742229 0.24479964  8.064648 2.600142e-13</code></pre>
</div>
</div>
<p>Again, other than the p values being reported to slightly more significant figures, the results for all values in our bespoke table are identical to those reported in the statistical model summary report.</p>
<p><strong>QED</strong>: As we have been able to reconstruct all values in the statistical summary table from scratch, we have now confirmed we understand exactly what this summary table reports, and what steps and processes were involved in producing these values.</p>
</section>
</section>
<section id="reflection" class="level2">
<h2 class="anchored" data-anchor-id="reflection">Reflection</h2>
<p>Does what the statistical summary table produces, and the way it’s derived, surprise you? Are the hypotheses it tests hypotheses that actually interest you from a substantive point of view? Given the P values here are really just rules of thumb about whether you might ‘get away with’ using a slightly simpler model, rather than really informed hypotheses about the world as it might be if a relationship you think you see between two variables were not observed (i.e.&nbsp;a Null distribution derived from first principles), what’s usually tested in statistical summary tables, and the P values reported, are often not as meaningful or relevant as many (ab)users of statistic model outputs tend to assume.</p>
<p>One thing the summary model does seem to be suggesting is that, maybe, we can ‘get away’ with a model that drops the term <code>Sepal.Width</code>; this is because this is the only term in the coefficients table with a P value of less than 0.01. (If we were to use the standard p value threshold of 0.05 then there are no candidate terms for dropping.) A model without <code>Sepal.Width</code> would be an example of a restricted model, excluding the less statistically significant term, where the unrestricted model would then be the model we currently have. Let’s construct this restricted model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mod_restricted <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Petal.Width <span class="sc">+</span> Sepal.Length <span class="sc">+</span> Species, <span class="at">data =</span> iris)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_restricted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Species, 
    data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.76508 -0.15779  0.01102  0.13378  0.66548 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -1.45957    0.22387  -6.520 1.09e-09 ***
Petal.Width        0.50641    0.11528   4.393 2.15e-05 ***
Sepal.Length       0.55873    0.04583  12.191  &lt; 2e-16 ***
Speciesversicolor  1.73146    0.12762  13.567  &lt; 2e-16 ***
Speciesvirginica   2.30468    0.19839  11.617  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2664 on 145 degrees of freedom
Multiple R-squared:  0.9778,    Adjusted R-squared:  0.9772 
F-statistic:  1600 on 4 and 145 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Let’s compare the summary from the restricted model with the summary from the full model again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width + 
    Species, data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.78396 -0.15708  0.00193  0.14730  0.65418 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -1.11099    0.26987  -4.117 6.45e-05 ***
Petal.Width        0.60222    0.12144   4.959 1.97e-06 ***
Sepal.Length       0.60801    0.05024  12.101  &lt; 2e-16 ***
Sepal.Width       -0.18052    0.08036  -2.246   0.0262 *  
Speciesversicolor  1.46337    0.17345   8.437 3.14e-14 ***
Speciesvirginica   1.97422    0.24480   8.065 2.60e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2627 on 144 degrees of freedom
Multiple R-squared:  0.9786,    Adjusted R-squared:  0.9778 
F-statistic:  1317 on 5 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>One thing we notice is that, as a result of dropping the coefficient on the term <code>Sepal.Width</code>, all other coefficients change: the standard errors of these coefficients tend to reduce a bit, as we might expect now the data budget can be shared a bit more generously, but at the same time the values in the Estimate column, which gives the point estimates for each coefficient, have also changed. So, dropping one term doesn’t just improve the precision of the estimates of the other terms, but the centres (point estimates) of those terms as well.</p>
<p>The fact the P value on the t test for the <code>Sepal.Width</code> term was not statistically significant at ‘p &lt; 0.01’ gave a <em>signal</em> that <em>maybe</em> that term was a candidate for dropping from the model. But it didn’t actually demonstate that the restricted model, which excludes this term, is better than the unrestricted model that contained the term.</p>
<p>What might be a better comparison between the models, now we’ve gone to the trouble of specifying and fitting the restricted model, and have seen that the coefficients’ point values as well as standard errors have changed? Well, we can compare how well both the restricted and unrestricted models fit the observed data. Though it’s likely the unrestricted model will have slightly better fit to the data, just because more coefficients in a model provides more ways a model can ‘flex’ to the observed data (even if the coefficients were for variables that are just random numbers, that don’t provide any real predictive information for the response variable), a <em>statistically significant</em> difference in model fit between the unrestricted and restricted models suggests that the unrestricted model may be worth keeping, even though it’s stretching the data budget further.</p>
<p>Statistically significant? Doesn’t this imply another hypothesis test, with another test statistic to be compared against another Null distribution? Yes it does. When comparing two linear regression models in this way, the test statistic - which is a summary measure of differences in model fit between the two models - is known as the <strong>F score</strong>, and the Null distribution is an <strong>F distribution</strong>. For better or worse, we can elide the algebraic derivations and reasoning behind this particular test, and just be aware that, if we pass an unrestricted and a resticted model as the first two arguments to R’s <code>anova()</code> (Analysis of Variance) function, then the F test comparing the quality of fit of the restricted and unrestricted models is performed:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>f_test_results <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_full, mod_restricted) </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>f_test_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width + Species
Model 2: Petal.Length ~ Petal.Width + Sepal.Length + Species
  Res.Df     RSS Df Sum of Sq      F  Pr(&gt;F)  
1    144  9.9397                              
2    145 10.2880 -1  -0.34835 5.0468 0.02619 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Here the <code>anova()</code> function:</p>
<ul>
<li>reports that two models are being compared;</li>
<li>numbers these models model 1 and model 2;</li>
<li>reports the residual sum of squares (RSS) for both models (i.e.&nbsp;a summary statistic of the error between observed and predicted response variables);</li>
<li>reports the degrees of freedom for both models;</li>
<li>notes the difference between the degrees of freedom between the models</li>
<li>notes the difference between the RSS of the two models (this is reported in the column <code>Sum of Sq</code>);</li>
<li>calculates an observed F statistic given the above information;</li>
<li>performs an F test with this information, and reports a P value</li>
</ul>
<p>Note the P value reported from this F test here. Let’s compare it with the P value on the <code>Sepal.Width</code> coefficient from the F test. We can extract and compare these P values as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="fu">summary</span>(mod_full))[<span class="dv">4</span>, <span class="st">'p.value'</span>] <span class="sc">|&gt;</span> <span class="fu">unlist</span>() <span class="ot">-&gt;</span> p_from_t</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="fu">anova</span>(mod_full, mod_restricted))[<span class="dv">2</span>, <span class="st">'p.value'</span>] <span class="sc">|&gt;</span> <span class="fu">unlist</span>() <span class="ot">-&gt;</span> p_from_f</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>p_from_t</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   p.value 
0.02619373 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>p_from_f</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   p.value 
0.02619373 </code></pre>
</div>
</div>
<p>It looks like the P value from the F test and from the t tests are identical. Let’s check this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">identical</span>(p_from_t, p_from_f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>They’re not <em>exactly</em> identical, but they seem very close to the number of decimal points presented, and would lead to the same conclusions about whether to exclude the <code>Sepal.Width</code> variable: If we are using a <code>P &lt; 0.05</code> threshold as our decision rule about whether to keep or exclude a variable from a model, then both approaches essentially lead to the same conclusion: keep this variable.</p>
<p>So, in this example, the row-wise t tests on the coefficients of the full model provide a useful shortcut means of assessing whether to keep or drop a variable, without having to build as many restricted models as there are coefficients, and then running F tests on the full model against each of the restricted models. Back when the level of computing time required to fit each model was substantial - such as when it took teams of people employed as computers days to perform the calculations necessary - the t test on the full model would have helped save a lot of resource.</p>
<p>For at least the last two or three decades, however, the practical savings involved in relying on t tests of one model, rather than actually performing a series of pairwise restricted/unrestricted model comparisons, are tiny: maybe a couple of minutes of code-writing time, and a second or two of computing time. However, the standard statistical model outputs have been around long enough that, for better or worse (hint: for worse), star gazing on P values based on t tests of coefficients of the unrestricted model has assumed a kind of totemic status in statistical analysis. It’s become seen as <em>the way</em> of doing robust quantitative scientific research on all manner of topics, in a way that provides <em>dispositive proof</em> for against a particular claim of <em>significance</em>. As mentioned previously, this is the cult of statistical significance.</p>
</section>
<section id="stepping-with-aic-a-different-way-of-assessing-whether-we-can-prune-a-model" class="level2">
<h2 class="anchored" data-anchor-id="stepping-with-aic-a-different-way-of-assessing-whether-we-can-prune-a-model">Stepping with AIC: A different way of assessing whether we can prune a model</h2>
<p>There are some other ways of trying to work out whether we can trim terms from a model specification, which don’t carry the kind of baggage of ritualised overinterpretion that the t test of the standard statistical model summary has acquired. One approach is to use the <code>step()</code> function, which runs an algorithm for searching through model specifications on our behalf. Let’s see what happens when we ask the <code>step()</code> function if it thinks it can shave off any terms without significantly harming the model fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(mod_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-395.12
Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width + Species

               Df Sum of Sq     RSS     AIC
&lt;none&gt;                       9.9397 -395.12
- Sepal.Width   1    0.3484 10.2880 -391.95
- Petal.Width   1    1.6974 11.6371 -373.47
- Species       2    4.9133 14.8529 -338.87
- Sepal.Length  1   10.1075 20.0472 -291.88</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width + Sepal.Length + Sepal.Width + 
    Species, data = iris)

Coefficients:
      (Intercept)        Petal.Width       Sepal.Length        Sepal.Width  
          -1.1110             0.6022             0.6080            -0.1805  
Speciesversicolor   Speciesvirginica  
           1.4634             1.9742  </code></pre>
</div>
</div>
<p>What the <code>step()</code> function did is largely equivalent to running a series of F tests, comparing the unrestricted model <code>mod_full</code> against a series of partially restricted models, each of which drop a single term from the original specification. <code>step()</code> isn’t exactly equivalent, however, because it uses a different metric, rather than the F test, to compare the quality and efficiency of fit of the models, called <strong>AIC</strong>, which stands of Akaike’s Information Criterion (or ‘An Information Criterion’). The purposes of AIC include:</p>
<ul>
<li><ol type="1">
<li>to quantify the trade-off between model fit and model complexity in a single value, a <em>penalised</em> model fit score;</li>
</ol></li>
<li><ol start="2" type="1">
<li>to generalise the intuition of F tests beyond standard linear regression, by using a summary statistic based on log-likelihood;</li>
</ol></li>
<li><ol start="3" type="1">
<li>to allow for comparison between models that are not nested.</li>
</ol></li>
</ul>
<p>The AIC is a summary measure of how well the model fits the data <em>as well as</em> model complexity. Given a single dataset <span class="math inline">\(D\)</span> an ensemble of potentially viable model specifications <span class="math inline">\(\{M_1, M_2, M_3, .., M_K\}\)</span> could be fit to it. Each of these models will differ both in terms of model fit and model complexity. The formula for AIC is <code>-2log-likelihood + 2n</code>, where n is the number of parameters in the model. The key observation here is that better fit of the model to the data, as represented by log likelihood, counts negatively to the AIC value, whereas more model complexity, repesented by the number of parameters, count positively to the score. Quality of fit and model complexity therefore tug the AIC score in opposite directions.</p>
<p>Note that, whereas with the F test the decision rule is based on a Null distribution and a P value below a critical threshold, and so is a form of statistical significance test, when using AIC the decision rule is usually simpler: <em>pick the smallest number</em>.</p>
<p>What the <code>step()</code> function has done is:</p>
<ul>
<li>Fit the model with all specified parameters, and returned the AIC (<code>-395.12</code>); this is shown in the <code>&lt;none&gt;</code> row.</li>
<li>Fit the model with the coefficient <code>Sepal.Width</code> removed, and returned the AIC for this slightly simpler model (<code>-391.95</code>). It has also reported that this model has one fewer degree of freedom (the <code>Df</code> column) than the starting model.</li>
<li>Done the same for each of the other three coefficients in the model: <code>Petal.Width</code>, then <code>Species</code>, then <code>Sepal.Length</code>.</li>
</ul>
<p>After doing this, the <code>step()</code> procedure has determined that the original model, with four coefficients, has superior (lower) AIC than all four alternative candidate models.</p>
<p>As a result of this, the <code>step()</code> procedure has decided to stop: it cannot identify any single deletion from the model that results in a better (lower) AIC as compared with the original, unrestricted model type.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>In this post, we’ve shown how the standard statistical summary outputs for linear regression model are derived, and presented a framework for thinking about the role of such model outputs in helping us consider whether we can ‘get away’ with a slightly simpler model specification. The role of statistical model outputs within this framework - in which they constitute just one step and piece of an interative process - is a far cry from the way such model outputs are often interpreted: as an authoritative source of ‘truth’ as to whether one thing is or is not (substantively) ‘significant’. In some cases, such as within a well designed and well conducted randomised control trial, the statistical significance of a coefficient may well answer the question of interest authoritatively; but in many cases the results from these statistical model summaries are vastly (and routinely) overinterpreted.</p>
<p>Having derived the components of standard statistical model outputs, we can hopefully see at least two problems with star-gazing such tables:</p>
<ul>
<li><strong>The problem of multiple testing</strong>: If we do not start with a specific hypothesis, and simply star-gaze a large table of coefficients, we are more likely to see a statistically significant result by chance alone.</li>
<li><strong>The problem of inappropriate Null hypotheses</strong>: For instance, if we are fairly sure that, were a predictor to have an effect on the response variable, it would be in the positive direction, then our test should be one-sided. By contrast the P values reported in statistical model summaries are for two sided tests.</li>
</ul>
<p>To help think further about the latter point, let’s return to <a href="../../../../posts/glms/complete-simulation-example/lms-are-glms-part-11/index.html">the model specification that was the focal example of the the third section of my statistics series</a>. This specification is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ToothGrowth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   len supp dose
1  4.2   VC  0.5
2 11.5   VC  0.5
3  7.3   VC  0.5
4  5.8   VC  0.5
5  6.4   VC  0.5
6 10.0   VC  0.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>mod_full_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(len <span class="sc">~</span> <span class="fu">log</span>(dose) <span class="sc">*</span> supp, <span class="at">data =</span> ToothGrowth)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>mod_full_int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = len ~ log(dose) * supp, data = ToothGrowth)

Coefficients:
     (Intercept)         log(dose)            suppVC  log(dose):suppVC  
          20.663             9.255            -3.700             3.845  </code></pre>
</div>
</div>
<p>The formula for this model specification is <code>len ~ log(dose) * supp</code>, where the <code>*</code> term indicates that interaction terms should be added relating the terms before and after the <code>*</code> symbol. In this case these terms are <code>log(dose)</code> and <code>supp</code>, and the interaction term between these two terms is <code>log(dose):suppVC</code>. The summary report is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = len ~ log(dose) * supp, data = ToothGrowth)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.5433 -2.4921 -0.5033  2.7117  7.8567 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       20.6633     0.6791  30.425  &lt; 2e-16 ***
log(dose)          9.2549     1.2000   7.712  2.3e-10 ***
suppVC            -3.7000     0.9605  -3.852 0.000303 ***
log(dose):suppVC   3.8448     1.6971   2.266 0.027366 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.72 on 56 degrees of freedom
Multiple R-squared:  0.7755,    Adjusted R-squared:  0.7635 
F-statistic:  64.5 on 3 and 56 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Say we are interested in investigating the following hypothesis:</p>
<blockquote class="blockquote">
<p>The supplement allocated (VC or OJ) does not influence growth (the <code>len</code> variable)</p>
</blockquote>
<p>Which of the four coefficients in the model summary need to be looked at, and which associated p value, in order to evaluate this hypothesis?</p>
<p>Now, because there’s an interaction term between <code>log(dose)</code> and <code>suppVC</code> included in the model, there are two variables which include <code>suppVC</code>, and represent a path of influence through which the selection of supplement could affect the response variable, <code>len</code>. These are:</p>
<ul>
<li>The direct path of influence: <code>suppVC</code></li>
<li>The indirect path of incluence: <code>log(dose):suppVC</code></li>
</ul>
<p>The hypothesis, as stated, does not distinguish between these two paths of influence. Therefore, <em>no single coefficient and associated P value represents the alternative hypothesis being considered</em>.</p>
<p>So, in this example, we need to construct our own restricted model for comparison, and use the F test or equivalent. Our restricted model would be the one in which both the terms for the direct and indirect paths of influence are removed, i.e.&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>mod_restricted_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(len <span class="sc">~</span> <span class="fu">log</span>(dose), <span class="at">data =</span> ToothGrowth)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_restricted_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = len ~ log(dose), data = ToothGrowth)

Residuals:
   Min     1Q Median     3Q    Max 
-8.061 -3.274 -1.061  3.063 10.434 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  18.8133     0.5496   34.23   &lt;2e-16 ***
log(dose)    11.1773     0.9711   11.51   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.257 on 58 degrees of freedom
Multiple R-squared:  0.6955,    Adjusted R-squared:  0.6902 
F-statistic: 132.5 on 1 and 58 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We can now compare the unrestricted model, with both paths of influence, with the restricted model, with no paths of influence, as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_full_int, mod_restricted_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: len ~ log(dose) * supp
Model 2: len ~ log(dose)
  Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
1     56  774.89                                  
2     58 1051.26 -2   -276.37 9.9865 0.0001953 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Here the <code>anova()</code> reports that the restricted model represents a model containing two fewer degrees of freedom, rather than a single degree of freedeom decrement. The associated P value is very low, below <code>P &lt; 0.001</code>, suggesting the supplement should be retained as a predictor of the response in the model.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This (fairly long) post has aimed to <em>demystify</em> and <em>disenchant</em> the standard statistical model outputs people are presented with after running a regression model. <em>Demystify</em>, in the sense of showing exactly how the standard model summary outputs are calculated, and how we can generate them from scratch. And <em>disenchant</em>, in the sense of trying to break the spell of the <strong>Cult of Statistical Significance</strong> that has long pervaded and perverted quantitative research throughout much of academia and the clinical sciences.</p>
<p>I have suggested that the standard summary outputs from statistical regression models definitely have some value, and are inexpensive ways of thinking about the potential balance and trade-off between models in terms of their complexity (number of parameters) on the one hand, and their fit (deviation between observed and predicted outputs) on the other hand. I’ve argued that models should be thought of mainly as data reduction tools, and the standard summary outputs as cheap advice on how to best spend a fixed data budget, i.e.&nbsp;the number of observations in the dataset.</p>
<p>However, the magical, totemic position that these model outputs, and especially the stars printed alongside coefficients, has acquired over many decades ultimately - in my view - represents a disservice and drag to applied quantitative science. The reliance on interpreting individual coefficients as either ‘statistically significant’ or ‘not statistically significant’ has the ironic consequence of rendering the main presented output of <em>quantitative</em> models as something <em>qualitative</em>: to be (statistically significant), or not to be. That is the question (those who apply this approach assume).</p>
<p>Many of the individual elements discussed in this post have been introduced or utilised in earlier posts I’ve written. For example I first discussed the overreliance on interpreting individual coefficients as quantities of interest in <a href="../../../../posts/glms/intro-to-glms/lms-are-glms-part-04/index.html">this post</a> on beta values; I made use of terminology like restricted and unrestricted model, and AIC and anova, in <a href="../../../../posts/glms/complete-simulation-example/lms-are-glms-part-11/index.html">this post</a> on selecting a model specification; and I introduced hypothesis testing on <a href="../../../../posts/glms/hacker-stats/infer-introduction/index.html">this post</a> on the infer package. However this is the first post where I’ve tried to focus on the concepts of P values and statistical significance of the type most people are familiar with. I hope this post therefore manages to tie these disparate pieces together a bit more coherently.</p>
<p>Thanks for reading!</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mccloskey_cult_2008" class="csl-entry" role="listitem">
McCloskey, Deirdre, and Steve Ziliak. 2008. <em>The <span>Cult</span> of <span>Statistical</span> <span>Significance</span>: <span>How</span> the <span>Standard</span> <span>Error</span> <span>Costs</span> <span>Us</span> <span>Jobs</span>, <span>Justice</span>, and <span>Lives</span></em>. Ann Arbor, MI: University of Michigan Press. <a href="https://doi.org/10.3998/mpub.186351">https://doi.org/10.3998/mpub.186351</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'alternate';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="JonMinton/BlogComments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</body></html>