---
title: "Death, Dying and Darwin"
subtitle: "Preserving capacity for conscious experience is overvalued; preventing avoidable suffering is under-valued"
draft: true
author: "Jon Minton"
---

> I want to propose a framework in which we can place the various design options for brains, to see where their power comes from. It is an outrageously oversimplified structure, but idealization is the price one should often be willing to play for synoptic insight. I call it the Tower of Generate-and-Test; as each new floor of the Tower gets constructed, it empowers the organisms at each level to find better and better moves, and find them more efficiently. 

> In the beginning - once the pump has been primed - there was Darwinian evolution of species by natural selection. A variety of candidate organisms were blindly generated by more or less arbitrary pressures of recombination and mutation of genes. These organisms were field-tested, and only the best designs survived. This is the ground floor of the Tower. Let is call its inhabitants *Darwinian creatures*.

FIRST FIGURE HERE. 

> This process went through many millions of cycles, producing many wonderful designs, both plant and animal, and eventually among its novel creations were some designs with the property of phenotypic plasticity. The individual candidate organisms were not wholly designed at birth, or, in other words, there were elements of their design that could be adjusted by events that occurred during the field tests. [...] Some of these candidates, we may suppose, were no better off than their hard-wired cousins, since they had no way of favoring (selecting for an encore) the behavioral options they were equipped to "try out," but others, we may suppose, were fortunate enough to have wired-in "reinforcers" that happened to favor Smart Moves, actions that were better for their agents. These individuals thus confronted the environment by generating a variety of actions, which they tried out, one by one, until they found one that worked. We may call this subset of Darwinian creatures, the creatures with considerable plasticity, *Skinnerian creatures*, since, as B. F. Skinner was fond of pointing out, operant conditioning is not just analogous to Darwinian natural selection; it is continuous with it. [...]

SECOND FIGURE HERE 

> Skinnerian conditioning is a fine capacity to have, so long as you are not killed by one of your early errors. A better system involves *preselection* among all the possible behaviors or actions, weeding out the truly stupid options before risking them in the harsh world. We human bings are creatures capable of this third refinement, but we are not alone. We may call the beneficiaries of this third story in the tower *Popperian creatures*, since, as Sir Karl Popper once elegantly put it, this design enhancement "permits our hypotheses to die in our stead." Unlike the merely Skinnerian creatures, many of whom survive only because they make lucky first moves, Popperian creatures survive because they're smart enough to make better-than-chance first moves. Of course, they're just lucky to be smart, but that's better than just being lucky. 

THIRD FIGURE HERE 

> But how is this preselection in Popperian agents to be done? Where is the feedback to come from? It must come from a sort of *inner environment* - an inner something-or-other that is structured in such a way that the surrogate actions it favors are more often than not the very actions the real world would also bless, if they were actually performed. In short, the inner environment, whatever it is, must contain lots of *information* about the outer environment and its regularities. Nothing else (except magic) could provide preselection worth having. [...]

> [...]

> We do not differ from all other species in being Popperian creatures, then. Far from it; mammals and birds and reptiles and fish all exhibit the capacity to use information from their environemnts to presort their behavioral options before striking out. We have now reached the story of the Tower on which I want to build. Once we get to Popperian creatures, creatures whose brains have the potential to be shaped into inner enviornments with preselected prowess, what happens next? How does new information about the outer evironment get incorporated into these brains? This is where *earlier* design decisions come back to haunt - to constrain - the designed. In particular, choices that evolution has already made between need-to-know and commando-team now put major constraints on the options for design improvement. If a particular species' brain design has already gone done the need-to-know path with regard to some control problem, only minor modifications (fine tuning, you might say) can be *readily* made to the existing structures, so the only hope of making a major revision of the internal environment to account for new problems, new features of the external environment that matter, is to *submerge* the old hard-wiring under a newe layer of pre-emptive control. [...] It is these higher levels of control that have the potential for vast increases in versatility. And it is at these levels in particular that we should look for the role of language (when it finally arrives on the scene), in turning *our* brains into virtuoso preselectors. 

> We engage in our share of rather mindless routine behavior, but our important acts are often directed on the world with incredible cunning, composing projects exquisitely designed under the influence of vast libraries of information about the world. The instinctual actions we share with other species show the benefits derived from the arrowing explorations of our ancestors. The imitative actions we share with some higher animals may show the benefits of information gathered not just by our ancestors, but also by our social groups over generations, transmitted nongenetically by a "tradition" of imitation. But our more deliberatively planned actions show the benefits of information gathered and transmitted by our conspecifics in every culture, including, moreover, items of information that no single individual has embodied or undestood in any sense. And though some of this information may be of rather ancient acquisition, much of it is brand-new. When comparing the time scales of genetic and cultural evolution, it is useful to bear in mind that we today - every one of us - can *easily* understand many ideas that were simply unthinkable *by the geniuses* of our grandparents' generation! 

> The successors to mere Popperian creatures are those whose inner environments are informed by the *designed* portions of the outer enviornment. We may call this sub-sub-subset of Darwinian creatures *Gregorian creatures*, since the British psychologist Richard Gregory is to my mind the pre-eminent theorist of the role of information (or, more exactly, what Gregory calls Potential Intelligence). Gregory observes that a pair of scissors, as a well-designed artifact, is not just the result of intelligence, but an endower of intelligence (external Potential Intelligence), in a very straightforward and intuitive sense: when you give someone a pair of scissors, you enhance his potential to arrive more safely and swiftly at Smart Moves. 

> Anthropologists have long recognized that the advent of tool use accompanied a major increase in intelligence. Chimpanzees in the wild fish for termites with crudely prepared fishing sticks. This fact takes on further significance when we learn that not all chimpanzees have hit upon the trick; in some chimpanzee "cultures," termintes are a present but unexploited food source. That reminds us that tool use is a two-way sign of intelligence; not only does it *require* intelligence to recognize and maintain a tool (let alone fabricate one), but tool use *confers* intelligence on those who are lucky enough to be given the tool. The better designed the tool (the more information embedded in its fabrication), the more Potential Intelligence it confers on its user. And among the pre-eminent tools, Gregory reminds us, are what he calls "mind-tools": words. 

FIGURE HERE 

> Words and other mind-tools give a Gregorian creature an inner environment that permits it to construct ever more subtle move-generators and move-testers. Skinnerian creatures ask themselves, "What can I do next?" and haven't a clue to answer until they have taken some hard knocks. Popperian creatures make a big advance by asking themselves, "What should I think about next?" before they ask themselves, "What should I do next?". Gregorian creatures take a big step by learning how to think better about what they should think about next - and so forth, a tower of further internal reflections with no fixed or discernable limit. 

> What happens to a human or hominid brain when it becomes equipped with words? In particular, what is the shape of this environment when words first enter it? It is definitely *not* an even playing field or a *tabula rasa*. Our newfound words must anchor themselves on the hills and valleys of a landscape of considerable complexity. Thanks to earlier evolutionary pressures, our innate quality spaces are species-specific, narcissistic, and even idiosyncratic from individaul to individual. [...]

> [...]

> [...] Our human brains, and only human brains, have been armed by habits and methods, mind-tools and information, drawn from millions of other brains which are not ancestral to our own brains. This, amplified by the *deliberative*, *foresightful* use of generate-and-test in science, puts our minds on a different plane from the minds of our nearest relatives among the animals. This species-specific process of enhancement has become so swift and powerful that a single generation of its design improvements can now dwarf the R-and-D efforts of millions of years of evolution by natural selection. [...] They are joined by an innovation that has invated our brains and no others: language. I am not making the foolish claim that all our brains are knit together by language into one gigantic mind, thinking its transnational thoughts, but, rather, that each individual human brain, thanks to its communicative links, is the beneficiary of the cognitive labors of the others in a way that gives it unprecedented powers. 