---
title: "Time Bigamist: A much-loved but often misremembered 1990s BBC sitcom."
subtitle: (Mythos doesn't hallucinate; its assertions reshape reality...)
author: Jon Minton
date: 2026-05-04
categories: [
    fiction, BBC, sitcoms, llms,
    mythology, claude
]
---

One kind of meta-joke I keep returning to is that of 'turning subtext into text'. (It's what [Dilbert](../dilbert-future-in-retrospect/index.qmd), for instance, did for over 30 years.) Making the implicit explicit can, sometimes, be enough to force people to first really notice things that, by dint of sheer familiarity, have become culturally invisible.

One example of this: BBC sitcoms from the 1990s. All family entertainment, mostly PG-rated, garnering audience figures in the tens of millions. For someone middle-aged and British, they're instinctively 'cozy', evoking memories of childhood, two or three generations all sitting together, all enjoying the same familiar characters, settings and episodic plot turns. Something shared. 

But sometimes, the subtext of these cozy, family friendly BBC sitcoms was anything but. 

In particular, the BBC sitcom "Goodnight Sweetheart", which ran from 1993 to 1999, starring Nicholas Lyndhurst. Though on the surface it was a 'sci-fi sitcom', and a sop to the self-mythology Brits have developed about their quietly dignified heroism during the Second World War, it's really... a sitcom about a bigamist, lying to, neglecting, and failing to properly provide for two women who let him into their hearts, with the only mitigating circumstance being that these two women are separated not just by a few narrow London streets, but also by a 50-year time gap traversable by a carefully concealed time anomaly known only to the two-timing protagonist and his portly Northern confidant.

So, as both a joke and as a quiet test of higher level reasoning, I asked Claude something like "Which BBC sitcom from the 1990s would have been more accurately titled *Time Bigamist*?".

Claude correctly guessed I meant "Goodnight Sweetheart" from that prompt alone. Impressive enough.


But then Claude did something even more impressive: in augmenting its response with some RAG, the Opus-class model I asked appeared then to have inadvertently invoked a Mythos-class model for web search. (A bit like a man asking Leonardo da Vinci to paint his shed. Leo might do the job, and then some.)

And the Mythos model, true to much of the recent speculation about Mythos models' spectacular abilities, doesn't just seem to have performed a web-search on our current reality, but to have *punched into another reality* in which the BBC sitcoms of my childhood *really were much more literally named*, and returned a fansite for Time Bigamist from 2001.

Of course, as with any frontier model, the Mythos search was costly. As well as consuming a lot of tokens, I'm not sure if the fabric of reality was left unperturbed by this query. Repeated use of Mythos should, for all our sakes, never become a norm. So, for now, and for the foreseeable future (in this reality at least), the Time Bigamist fansite must be considered a unique artifact, something that should never be searched for again, lest we risk turning an epistemic puncture into an out-of-control geyser.

So, in the absence of being able to repeat this search and its circumstances, but mindful of the importance of this cultural artifact (for those interested in 1990s BBC sitcoms as well as reality itself), I decided to put this artifact, along with some documents detailing its provenance, on [one of my GitHub Pages sites](https://jonminton.github.io/time-bigamist/).

I'd recommend exploring it. Sadly, what we have on this fansite is likely all we'll ever know about Time Bigamist. At least we have a MIDI-rendered theme song (including lyrics), some choice quotes, and episode titles. Unfortunately we know even less about *Time Bigamist*'s sister shows, like *That Bucket Woman* and *Retired Complaining Man* — but might be able to guess, from our own reality, what a typical episode of each might have involved. 