---
title: "Link-breaking Spring Clean"
author: "Jon Minton"
date: "2024-05-31"
categories: [quarto, website, statistics]
---

As frequent/occasional viewers of this site might notice, the contents and header structure of this blog have changed: Instead of a single statisics listing page, I've now created a 'Statistics & Data Science' listing button, which then expands to reveal three specific listing pages: 

- **Statistical Theory & Applications**: My series on re-then-de-mystifying statistical inference, reintroducing almost all models as 'types of' generalised linear model, and then showing the implications of this framing for better understanding how models work and what we can do with them. 
- **Tardy Tuesday**: My growing collaborative series where, each week, my colleagues and I try to get information out of the latest TidyTuesday dataset from Posit. 
- **Hand Drawn Statistics**: Largely a series of notes I occasionally make for myself to try to think through different aspects of statistics and statistical models, hand drawn in my overpriced (but still worth it) gridded Moleskine notebook, and then scanned from my phone as a series of images (using including my looming shadow and shaky-hand camera artefacts). As I tend to think and reason in quite a graphical way this is in some ways a more intuitive expression of statistical reasoning for me than more formally written material; I hope this material is useful to others too. 

If you look in the statistical theory & Applications section, you'll also see that I've attempted to break up the posts into sections: A core section and an additional section, and within the core section some further subdivision into three subsections: Introduction; Likelihood and simulation theory; a complete example. 

I hope this spring clean makes these resources easier to navigate and use than before. 

Unfortunately a number of internal links broke as a result of moving the posts around. I've fixed quite a lot of these, but *if you see any more broken links please leave a message as a comment in this post (github ID required), or contact me some other way.* 

