---
title: "Mickey 17 and the Economics of Life"
subtitle: "(It's not what you think"
author: "Jon Minton"
date: "2025-04-18"
categories: [films, sci-fi, life, economics, soul, memory, genes]
---

A few weeks ago I saw Mickey 17 at the local cinema. It's a fantastically frustrating colloid of a film, combining some extremely interested philosophical and sociological concepts with some characterisattions and performances that lack the verisimilitude of cartoon characters, and tiresome plot beats and action spectacles that seem the cost of doing business when producing a sci-fi film above a certain budget. The filmy separation between the profound and the ridiculous usually being Mark Ruffalo's face. Ruffulo's performances seem to channel Austen Powers era Mike Myers, but lack both Myers charisma nor self-awareness, and his every moment on screen caused my toes to curl and my perception of time to dilute towards infinity.

Setting aside the terrible aspects of the film - and I *am* trying to - at heart Mickey 17 follows some fascinating premises into some interesting places. In Mickey 17 a two-part solution to mortality has been invented. Bodies, and minds, can now be recorded and reproduced with perfect allacrity, the bodies manufactured by 3D bioprinters, the minds and memories constantly backed up and downloaded to newly fabricated bodies whenever the last living body happens to expire. Because of this new technology, nobody need ever die ever again. 

So far, so sci-fi-standard-fare. What are Star Trek's teleporters, for example, but mechanisms for making replicates of recently existng bodies and minds, albeit with the thrice coupled technology of perfect annihilation of the body in the original location - so as to skim over most of the awkward dilemmas and paradoxes raised by such a device? 

Where Mickey 17 departs from the usual cliches, however, is in exploring the sociological ripples such a technology might produce. After initial enthusiasm, Humanity quickly turns hostile on the technology, its uses, and potential for abuse. The legal ramifications of certain edge cases - such as who might be criminally liable when two or more copies of an individual are fabricated and coterminously exist - are judged too head-spinningly confusing, and so this existence-shattering Pandora's Box, the solution to death itself, is by consensus and agreement firmly shut again, almost everywhere that humans call their home. 

Almost, but not completely. There are some people for whom, and some places where, immortality is still permitted. Neither the places nor the people are envied. The places are the rough edges of civilisation; the people: the unerclass of these inhospitable frontiers. 

Because, in Mickey 17, immortality is a *curse*, something only the indigent and desperate would ever agree to be exposed to. The title character, Mickey (or Mickey 1, perhaps), is deep in debt, and the creditors are impatient, violent, sadistic gangsters. Mickey needs money, and needs to be gone, and so volunteers to work on an advance party being assembled to settle a newly discovered ice planet. Each party member's station on the ship and colony will be an exaggerated variant of their station at home. Mickey, with less than nothing on Earth will therefore have less than nothing many times over in the colony.

What does this look like? Well, Mickey signs a contract, to work the dirtiest and most dangerous jobs that need to be done, jobs so nasty, and so dangerous, than no one else will touch. Worse: not event death is considered a valid excusal from fulfilling the terms of the contract in full. If (when) Mickey dies, he's simply reprinted and told to go back to work tomorrow. In the universe of Mickey 17, from from being a profoundly positive development, the solution to death has becomes a means of inventing something like the dalit class from the Indian caste system, and combining this with intentured servitude, creating opportunities for debt bondage so inescapable that even death itself cannot break it. 

Though little is made in the film of this association, in Mickey 17 the value of a life seems to be determined by the laws of supply and demand. When life is finite and death is final, life is valuable and precious. By contrast, for the Immortal Space Dalits, for whom life is plentiful and death merely an inconvenience, life is very cheap and so very unimportant. Like any other commodity, therefore, the value of a life falls as its supply increases, such as to become worthless once its supply becomes infinite. 

Skip forward from this premise one or two hours (to reiterate, time dilates whenever Mark Ruffalo starts chewing scenery) and the film ends. A social revolution has occurred on the colony, and Mickey regains his humanity. How? (**SPOILER ALERT**) By pressing down on a plunger that destroy's the one remaining replicator, and with this his curse of immortality. Mickey, like everyone else, now has just one life, one precious and finite life, and commits to live it as best as he can. 


Though featuring a mostly Anglo-American cast, Mickey 17 was written by a South Korean director. It is of course both reductive and fruitless to do so, but I do wonder whether the idea. that immortality could be more of a course than a blessing, may be easier to entertain for someone not raised in a broadly Judeo-Christian culture than for someone who has. Abrahamic faiths have faith in the Soul, that Cartesian separation from the physical realm that is doctrinally considered the True, Immortal Self that only briefly inhabits a physical vessel, a vessel that, in Christian theology at least, is seen to bring the Soul only weakness and temptation. By contrast, my crude sense is that East Asian theology is much more centred around Animism and Ancestor Worship (notwithstanding Christianity's popularity in South Korea), in which there seems less focus in immortality of the individual, because the individual themself is less fundamental to how people see themselves and the world they enter. Each individual already has something greater than themself to live in relation to, namely the family, their so-far immortal and unbroken chain of ancestors that lived before and gave rise to them, their household and their household of households. Or their Symbolic Family, whether it be Emperor and ethnonation, Corporation, or other form of Dear Leader. The need to serve - to work with diligence and loyalty towards the binding network of relations in which one was born - and to seek immortality through genes and other obdurate societal contributions made in life, rather than through the Immaterial Soul - is perhaps more readily assumed in such cultures than in the Anglo-American West. 

Personally, I've never found the concept of a Soul even desirable, let alone scientifically plausible. What would or a could a soul even be but some kind of driver without a vehicle? Imagine possessing those qualities of consceioussness, memory and sense of self, and with this the impulse to decide, but with absolutely no means of executing such decisions or expressing preference for doing one thing over another. And imagine this quality of being a bystander, to always see and think, but never to be able to act or change things from how they were always going to be, and imagine this being a state of existence that stregches from the Big Bang to the Heat Death of the Universe. Who would want that? Why would anyone want that, eitrher for themselves of those they knew? 

The alternative - that the capacity for consciousness stopes when the body stops - can't be a *bad* alternative. It is of couse the state of consciousness that all but a near-infinitesimal fraction of the unviers has or will ever manifest, and that for any congiguration of matter that was or will ever be possessing of consciousness, will or has only possessed such a state for only an infinitesimally tiny fraction of the time it has existed. To consider non-being in this way as a bad state is to place a negative valence on almost the entirety of all that ever was, is, and will ever be. 

And from what we now know about the quality of lived experience, we know that consciousness, in people, seems to be something of a sliding scale rather than a simple binary switch. Of course there's the obvious case of sleep, especially non-REM sleep, where consciousness has subsided to near nothingness. But two other, contrasting, states of waking life are alsu illustrative: the Default Mode Network (DMN), and Flow States. 

The Default Mode Network (DMN) describes the stereotypical patterns of coactivation and inhibition of brain regions observed while peopoe are, for need of a better term, 'idle' or 'doing nothing', i.e. not engaged in a particular form of mental or physical activity. When in the DMN, people are in fact almost never 'doing nothing', their brains tend to be very active, very much in contrast to some states of sleep and meditation. And what tends to be the nature of this DMN activity? Put crudely: *running simulations*, imaging themselves acting in the world, in different environments and with different people in those environments, in different ways, and imagining the different responses their actions will produce in each scenario. And then, after having simulated enough scenarios, trying to make decisions about how to act by comparing the expected outcomes of each scenario. 

The Flow State, by contrast, definese how the brain works when engaged in total pursuit of a single task or activity, an activity that is teetering on the edge of an individual's present abilities. The DMN and Flow State tend to be either-or: one's brain and body cannot be 'somewhere else', planning and deciding about future things to be doing, when it is fully engaged in demanding activities in the current moment. 

Crucially, the DMN and Flow State also tend to differ systematically both in terms of how *enjoyable* they are, and how *conscious* persons tend to be in each state. For most people, most of the time, the DMN is *not* an enjoyable or resful experince, but it is a very *conscious* experience. Often, though we may imagine the purpose of the DMN to be to make better decisions about the future, our simulations are about the past: about things that happened, where we acted a particular way and a particular outcome was realised, where instead we keep imagining ourselves having acted differently, and the outcomes turned out better. There's a word for this: *regret*. The DMN is at least as much a state of regret and rumination as it is a state of planning and decision-making. The DMN is also perhaps the state in which we are *most* conacious, continually evoking the notion of the self, in order then to throw it into a series of simulated scenarios, most of which result in some degree of harm, frustration or insult.

Conversely, in Flow States, the degree of consciousness tends to be much lower. The self - that body and mind *doing* - is already *doing the thing*, and so does not need to be constantly evoked and attended to with the deliberative intensity of the DMN. 

And in the Flow State, that state of being a *being doing* rather than *being deliberating*, affect tends to be highly positive rather than negative. 

Once again, if there were an immaterial soul, a bundle of self-conscious consciousness, attending to itself and deliberating about itself constantly, the experience of such a soul would likely be closer to that of the DMN rather than the Flow State. This is broadly what I mean by stating that the sould should not be something we desire to be true, even if it were more scientifically plausible. (As an example of what such a state might be like, think of the chilling poetic justice meted out to the ultimately villainous and tragic protagonist in Being John Malkovich: a puppeteer without a puppet, forever to exist as a by stander, even the agency to blink.)

Ultimately, then - and this may be another idea harder for those in Western Society to countenance - the continuation of a singular consciousness may not be a prize worth valuing and escalating to theological cornerstone. If so, what instead *is* something we should cherish and value, something that constitutes a more clearly positive quality that distinguishes the expereince a member of the species *Homo Sapiens sapiens* in the Twenty-First Century? 

I would suggest the answer in *memory*; more specifically, the layering of different kinds and qualities of memory available to us, including those that appear largely unique to Humanity. 

Let's start with the means of remembering we have in common with other animals: we have *brains*, and we have *genes*. For a single animal, a past expereince - at least those experiences that prove non-fatal, can be recalled - or re*felt* - leading to changes in future behaviour: once bitten, twice shy. It's these past experience that populate the overgrown simulation machines in our pre-frontal cortices - that enables and often locks us into our DMNs. Both other animal have this form of memory, and to an extent also the capacity to deliberate on future actions given lived history. 

And then there are genes, which reside in our bodies and propagate selectively based on the success with which they have solved those existential problems our ancestors repeatedly encounter, for hundreds, thousands, or even millions of years. The genes of humans and other animals are records of our deep past: they are what Richard Dawkins described as biological 'books of the dead', in his book *The Genetic Book of the Dead*. Dawkins made clear where the metaphor - of genes as books - needs qualifying. For the most part, Dawkins suggested, genes in organisms are *palimpsests*, in which the contents of pages are overwritten, rather than simply added or deleted. But genes *are*, *clearly*, a form of very deep memory.

Books, of course, bring us to our third form of memory: *cultural*. And it seems in our degree and variety of culturam memory and media that we really do seem unique by comparison with other andimals. Before there was the written word, therer was the spoken word, and with this a means of human groups remembering for potentially hundreds ofyears, and so of some form of communication to occur between two people who never existed at the same time - such as a boy knowing something impactful, that once happened to his great, great, great grandmother, who died generations before the boy was born. 

Oral records mutate, having much less fidelity than genes, and so the level of accuracy with which the generation 1 mother's experiences are recalled to generation 5 boy is likely to be quite low. However the processes by which stories and their elements are conveyed intergenerationally is itself likely to be far from random. To the extent that factual accounts evolved through cultural transmission into myths, and myths tend to have points of commonality even where groups have been separated for hundreds of years, we can infer something about the human mind, and the central characteristics and aspects of stories that tend to be memorable and impactful, that ring out through the ages. The biases and distortions of oral storytelling tell us not so much about what happened a few dozen or hundred years ago, but about our common selves, and so an important axpect of our deep genetic heritage. 

The written word, of course, allows for high fidelity communication and continuity over far more records than the spoken word allowed (at least, until the present era, where perhaps people born hundreds of years in the future will be able to see and hear exerpts of ourselves). The echoes of the past are partial - both in the sense that the symbols alone lose the texture of the context in which they emerged; and also because most people ahve been illiterate, and so largely voiceless through this medium. But the written word is a means through which polished thoughts, from minds in bodies that have long since perished, can live an active afterlife whose reach and influence can be orderds of magnitude greater than were ever achieved by the author while alive. 

And where words do contain knowledge, ways of better understanding the world, through either science or art, the written word, and other written accounts, mean that each new generation is able to start from a better place than the last. Written records, those obdurate living fossils of past struggles and solutions, those cystallised records of deep thought, are both waht fundamentally separates Humanity from the species *Homo Sapiens sapiens*, and the *other* means, along with DNA, through which those who have died can continue to support and influence those whom they are survived by. 

The written records isn't just art and science, however, and indeed hte most ipactful form of written record that surve their originators may be neither. The oldest written records perhaps ever identified were inscriptions on clay tablets (I think?), whcih become knwon as Linear B. For decades after being unearthed the contents remained a mystery, because the language was too unrelated to anything previously decoded. Once this ancient sipher was finally cracked the records turned out to be neither philosophical treatis nor scientific theories, but *accounts*, detailing *who owned or owed what to whom*. Such records of ownership may sound like an anticlimax, but is is through such records that the fruits of enterprise (and, more often, luck) can be passed alongside genetic lineages: it is through knowing who owes and owns what, and once deceased how such assets should be allocated, that the Household emerges as an entity yhat self-refreshes and propagates through the generations. The Household is neither a purely genetic nor purely social construct, but a symbiosis of these two forms of deep memory: *genes*, and *logos*. The death of a household member *might* lead to teh death or mortal wounding of a household. But with sufficient commitment to the principles of succession it need not do so. Like the Ship of Theseus, Households, and dynastic lineages thereof, can survive in one form or another for hundreds or thousands of years, bound together by both kinship, and conventions, and codefied legal documentation.

All of which is, in a roundabout way, my explantion for why I consider memory, rather than consciousness, to be the more important means through which the dead live beyond life. It's perhaps also why the core tenet of Mickey 17 - that immortality, a lack of closure of the consciousness of an individual, may be not a prize worth striving for, and may even be a curse - was so intriguing for me. 

For those precious few who've read this far, and the even fewer who read previous posts to this blog over hte last few months, it should be celar enough that this post isn't really a review of Mickey 17 at all (Although, to repeat, the premises really are fascinating, and Mark Ruffalo's performance really is terrible). Instead, it is another of an occasional series of my attempts to think carefully about hte life, death, and various forms of secular 'afterlife' left by my father, whom I suspect would, being more of a fan of space swashbucklers and the silliness they entail, have enjoyed Mickey 17 in a less ambiguous way than I did. The fundamental idea - that life is precious because rather than despite it being finite - is something I will try to remember, even if there are other aspects of the film I would prefer to forget. 