---
title: Three quality-of-life upgrades 
subtitle: RSS, wordcount, Repeated Measures
author: Jon Minton
date: "2025-08-24"
categories: [blog, web development, rss]
---

Here's a brief update to showcase three new improvements to this blog, along with a question (about RSSes), and some broader reflections: 

## RSS Feed

[Dan Olner](https://www.danolner.net/), who's been blogging longer than me, and usually with more interesting contents, made a request on Linkedin to enable RSS on the blog. Thankfully he supplied [the relevant link too](https://quarto.org/docs/websites/website-blog.html#rss-feed), and it all seems quite straightforward. If you now look towards the top right of the blog, you should be able to see the standard RSS icon, and clicking on it does seem to do *something*. 

- **Reflection**: This blog largely began with two aims: to have a practical application for practicing web development skills, and to have a place to develop and showcase my knowledge of statistical methods and data science. I think it's been successful on both fronts, but it's also become my platform for trying to think deeply about less technical and work-related domains, such as with my unpop series, and more recently the first short story I've finished writing for a number of years. Though writing is a practice I find purposive and enjoyable, and my writing is on topics and ideas that are interesting to me, they might not be of as much interest to persons reading just for the more techical materials. 
- **Question**: There are ways of creating multiple RSS feeds - such as one for more technical posts, and another for less technical posts. **Should I create separate RSS feeds for this blog?** Any views on this are much appreciated. 

## Word Count 

The subheader to the main blog page should now be procedurally updated to report the number of words the blog contains. At the time of writing the total estimated word count is slightly under 180,000 words, which if at all accurate means, since starting the blog in 2023, I've now put out around two books worth of content into the world.

Here's broadly how the word count works: 

- The `_quarto.yml` file in the root now has a pre-render argument, meaning each time the blog is rendered or published an R script is run.
- The R script recursively searches for all .qmd (quarto) files inside the project folder and its subfolders. Within each .qmd file it looks for anything that looks to be a word (i.e. something made up of letters and numbers, surrounded by spaces or punctuation) and adds that to a running total, until all has run out of .qmd files. 
- The R script then looks for the subtitle field in index.qmd, then inserts the new word count into the value component of that field. 

As with so much knowledge work, this solution was arrived at after asking a series of questions to an LLM. This time I tried Claude as I'd heard it was better at technical queries than most alternatives (though Claude are not Claude is: there are many versions). The solution I used was more inspired by, rather than derived directly from, any specific pieces of code it suggested. The subtle danger of using LLMs is that, though they promise to make coding tasks easier, they often instead just transfer the challenges from searching and writing code, to prompting and debugging code. Almost every code solution offered had bugs, and almost every suggested fix introduced new bugs. Knowing when to step away from just plugging in a new AI-generated code, and instead writing something loosely based on the code snippets, seems to be at least half the battle in using AI effectively. 

## Repeated Measures Header Image

My [article on repeated measures](../handdrawn-stats/repeated-measures/index.qmd) is the first post I've written that's entirely hand-written, and hand-drawn, using my [Remarkable](https://remarkable.com/) tablet. This meant the post comprised one single image. And in Quarto blogs the first image in a post is used, along with the title and first paragraph, to show previews of that post in the main blog page. This in effect meant the entire repeated measures post was used as its own preview, creating one very long and awkward side image for the post in the main blog page view. 

I've now corrected this by adding a smaller image, copied out from the main image, at the start of the repeated measures post. This should hopefully ensure the preview for the post is a bit less 'greedy', and can be more easily scrolled through with other blog entries in the main blog page. 

I'm still trying to come up with the best way of using Remarkable. For [my short story](../fiction/its-your-choice/index.qmd), for example, the entire story was first drafted with the device, then transcribed (manually, not automatically, as I don't trust the image-to-text conversion enough, especially for conveying formatting) onto a Quarto page. For the repeated measures blog, where I frequently swap between text and sketches, I think the Remarkable was fully appropriate. For the story, it was still useful because it meant I could take the tablet alone, without my computer, forcing myself to have fewer distractions while writing it. 

For the most recent post - my [book review of The Genius Myth](../unpop/the-what-is-a-genius-myth/9781787333246-jacket-large.webp) - I instead adopted more of a hybrid approach from the get-go, writing most of the text in Quarto, then having the Remarkable by my side for drawing sketches to go alongside the text. As the Remarkable syncs quite nicely and quickly with my macbook, this hybrid approach seemed to work pretty well, though it did involve taking more, rather than less, electronic equipment with me. 