---
title: "The Book of Nigel"
date: "2024-10-25"
author: "Jon Minton"
categories: [life, death, happiness, stories, faith, health, fiction]
---

## The Death of my Father

My father, [Nigel](https://www.linkedin.com/in/nigel-minton-39306a4/), died on Wednesday 16 October, after a series of strokes that began late that evening. He had been released from hospital the previous day, Tuesday 15 October, with a box of medication and information, after an angiogram the day before - Monday 14 October - that revealed three narrowed arteries, for each of which a stent was fitted. 

He was in hospital because, six days prior to his release, starting around midnight on Wednesday 9 October, he experienced a heart attack, which he initially attributed to indigestion. I was first alerted to him being in hospital late morning on Thursday 10 October. 

Before that, my father was fit and well, with no obvious health issues that impaired his ability to live a full and active life whatsoever. 

Up until Tuesday 8 October, my father had been planning to drive himself and my mother for five or more hours from the Midlands to my flat in Edinburgh on Friday 18 October, with a view to watching the [The Book of Mormon](https://en.wikipedia.org/wiki/The_Book_of_Mormon_(musical)) at 2.30pm with me on Saturday 19 October, with tickets he had bought much earlier in the year, and sent to me soon after. My partner, and my mother, both have even stronger instinctive aversions to musicals as a genre than I do, an aversion I was willing to put aside for the Book of Mormon given the show's subject matter and its apparent provenance as a continuation of ideas first explored in the South Park episode [All About Mormons](https://en.wikipedia.org/wiki/All_About_Mormons) in 2003. 

Fortunately, my partner was willing to overcome her aversion to musicals under the circumstances, and attend The Book of Mormon with me in my father's stead. Though declaring she would walk out if there were even a whiff of audience participation, fortunately there was none, and midway through the first half her arms uncrossed and she began laughing at some of the more vulgar and body-horrific aspects of the story. 

## The Book of Mormon: Faith, Myth and Meaning (*Spoiler Alert*)

[The Book of Mormon](https://en.wikipedia.org/wiki/The_Book_of_Mormon_(musical)) (the musical, not the book) continues exploring a theme apparent in [All About Mormons](https://en.wikipedia.org/wiki/All_About_Mormons): namely that practices and beliefs may be absurd in theory but wholesome and beneficial in practice. In All About Mormons a forensic, skeptical treatment of the veracity of the Book of Mormon (the book, not the musical) in terms of its claims to divine provenance is developed and prosecuted throughout most of the episode, and one of the child avatars of the show, Stan, takes up the mantel of prosecutorial skeptic, raising questions about logically inconsistent and implausible claims related to The Book to his new Mormon friend, Gary, who is both unerringly polite but also bound by his religious upbringing to accept the tenets of his faith without doubt or evidence. The Wikipedia summary of the conclusion of this episode is as follows: 

> Stan ends up shouting at the Mormons that they are ridiculous for believing in it without proof; they smile and patiently explain that it is a matter of faith, while Stan argues that it should be a matter of empirical evidence. He further lashes out at them for acting unusually nice all the time, claiming it blindsides stupid people like his father into believing in Mormonism (to which Randy Marsh responds with a determined "Yeah!").

> Stan's anger does not upset anyone in the Mormon family other than Gary, who confronts Stan and the other boys the next day, pointing out that he believes his religion does not need to be factually true because it still supports good family values and helping the poor. Gary also condemns their bigotry and ignorance in language that is normal for the main characters but extremely surprising and powerful coming from Gary, as he ends his dialogue telling Stan to "suck my balls". He walks away, leaving the boys in utter shock. The episode ends as Cartman, with a new-found respect for Gary, says "Damn, that kid is cool, huh?".

In The Book of Mormon, the musical, the argument is implicitly made that The Book emerged as a kind of ethnocentrist fan fiction to The Bible - part three to a sacred text that most Christians consider to have strictly only two parts (the New and Old Testament), and Jews to have just a single part (The Old Testament). This fan fiction, written by White European migrants(/'colonisers') to North America, continued the story of parts one and two by claiming that Jesus later visited North America, and that people who looked and acted much like the White Europeans who were the main readers (and in truth but not Truth authors) of the new part are a new Chosen People, much like the Israelites in part one and all followers of Jesus in part two. Mormonism, despite not making much sense as a series of literal claims, nevertheless came to function as a powerful binding mythos for persons who heard and became inspired by the stories, creating a distinct religious community that, despite (or possibly because of) much cultural conservatism and quirky behaviours, ultimately has kindness, commonwealth, conscientiousness and compassion at its heart. 

In the musical, two young adult Mormon elders, Kevin and Arnold, are dispatched to spread The Word to a location of the Church's (and not their) choosing. Their chosen destination: deepest Uganda. Whereas Elder Kevin is tall, slim, popular and knows The Book by heart, Elder Arnold is shorter, plumper, less popular and prone to spontaneous and uncontrollable fits of confabulation. With his short attention span and childlike love of popular sci-fi, we eventually come to learn that Elder Kevin has not actually read the book they are tasked with proselytizing. However, he is deeply enthusiastic about their mission, because it means having a popular new best friend who's duty bound to not leave him for two years. 

We then come to meet the villagers in Uganda, and the ranks of Mormon missionaries already stationed at the lodge. The other missionaries have a rolling tally of the number of Ugandan villagers they have successfully managed to baptise into the Church over the years: zero. Zero here, zero there, zero everywhere. No one in Uganda is interested in becoming a Mormon. The villagers have their own, more immediate problems: infectious diseases, insects that hatch and eat them from the inside, no functioning government and a tyrannical warlord who enforces female genital mutilation at gunpoint, lack of clean water and dysentery. The only God the villagers can bring themselves to believe in is one worthy of hatred and contempt, as surely no loving God would inflict such deep and relentless misery on them. 

On the few occasions the villagers grant the missionaries an opportunity to read something from The Book, it doesn't speak to the villagers the way the missionaries thought it would: the villagers are not interested in discussing how to quell and salve the stirrings of the soul when their bellies are rumbling, and any stirring sensations they feel inside are likely to be due to worm or maggot infestation. When the villagers ask the missionaries how The Book will help them with various challenges of staying alive and intact, the missionaries can find no useful advice to offer. 

After the more learned missionaries have tried and failed to enthuse the villagers, a comedy of errors and misunderstanding leads Arnold alone, who has not actually read The Book of Mormon, to explain its teachings. As Arnold reads the book aloud, villagers listening attentively, he quickly comes to realise just how little its precise words, events and stories resonate with the villagers and their concerns and experiences. To avoid disappointing the villagers with the dull, dry - and in places patently racist - words as written in the book, Arnold finds himself compelled to confabulate, blending Mormon characters and tropes with those borrowed from the villagers' lived experienced, and Arnold's own interior life of sci-fi fandom. 

Over many weeks Arnold, knowingly, and the villagers, unknowingly, transform The Book of Mormon into something almost entirely new. A new story where Joseph Smith dies of dysentery, becoming a Christ-like African martyr, where the Golden Plates become dinnerwear, and where Boba Fett, space torpedos, Darth Vader, and sacrificial groin frogs become important parts of the new iconography. 

The villagers, believing in the stories that Arnold and (inadvertently) they had developed, and believing that they now believed in The Book Of Mormon, then present their telling of the stories to senior visitors from the Mormon church, who have travelled to Uganda after hearing about the fabulous turn-around in baptism rates. The senior Mormons are first enthused, then shocked, then appalled, declaring the villagers, Arnold, and the rest of the missionaries apostates of the Church of Mormon. 

The play ends with a new variant of the opening song. The villagers, and the former Mormon elders, ring and knock on house doors, carrying a book whose Good News they wish to enthuse to others. This book, revealed in the final beat of the play: The Book of Arnold. So, the fanfic of the Book of Mormon now has a fanfic of its own. Arnold and the villagers, by departing from the precise details of the Book of Mormon, have nevertheless recreated its origins and rediscovered its original purpose: as a series of strange and fanciful stories that give meaning and succor to people experiencing particular forms of hardship, and that serve as a binding mythos and means of making life more tolerable and meaningful. 

## The Book of Nigel (*Spoiler Alert*)

I've never had a father die before. Of course no one has until it's happened. So I had no idea how I would respond and react to this news. Many people are quite compartmentalised in the ways they separate their professional, vocational and personal spheres of being, meaning if their behaviours were looked at as a whole they would appear quite inconsistent. [This anecdote](https://warfarehistorynetwork.com/article/bomber-harris-and-his-royal-air-force-bomber-command/), of an Air Commander being stopped for speeding by a police officer who told him, "You could have killed someone", and responding, "I kill thousands of people every night", is an example of someone acting with consistency across spheres, to such an extent as to appear pathological. 

I've discovered that I, too, appear to be pathologically consistent across spheres. Much of my professional life has involved analysing mortality statistics; thinking about circulatory disease, neoplasms, infectious diseases and dementias as the four main classes of competing cause that kill the vast majority of those who have survived infancy and fatal accidents; and when working as a health economist building models to better understand the risks and trade-offs that different forms of interventions can have on people's lives and experience of illness. One of my first experiences as a health economist was in evaluating a disease model made in Excel. The model was interactive, allowing parameters to be tweaked to allow structural sensitivity analyses to be performed. One option given, in the form of a checkbox that could be switched on or off, was labelled with the words "Allow WTD?". "What's WTD?", I asked a colleague. "Worse than death", he replied, meaning allow the model to include scenarios in which a person's quality of life to be so low as to be negative, meaning each moment they lived in such a state counted against their aggregate quality-adjusted lifeyears. 

My father lived to 97% of the latest published UK male life expectancy. I've calculated this. The life expectancy figures were for 2022, so it's possible once 2024 life expectancies are available the comparison may be a little less favourable: 95% perhaps. But 97% of average is what the latest available data implies.[^1]

[^1]: Since I started writing this post, the ONS estimates for 2021-2023 have become available. But please forgive me for choosing not to update this calculation.

But almost all of that 97% of UK male life expectancy was spent in good health, often very good health, apparently. Fairly recently he had been treated for a cancer, but of all places one could have a cancer, if one has to have a cancer, it was in just about the best location imaginable: the tip of one of his ears. One day he went to a hospital to have a short surgical procedure, in which a bit of his ear was removed, and the same day he was released. As he was a Star Trek fan I suggested a slightly pointier ear might be more a feature than a bug. No problems after that, just six monthly outpatient appointments. 

The term 'healthy life expectancy' (HLE) is used to distinguish those years lived in very good or good health, from those years lived overall (i.e. life expectancy, LE). [According to the ONS](https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthandlifeexpectancies/bulletins/healthstatelifeexpectanciesuk/between2011to2013and2020to2022#:~:text=Healthy%20life%20expectancy%20(HLE)%20at,%2C%2060.3%20years%20for%20females) the HLE for males is 62.4 years, as compared with [a LE of 78.6 years](https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthandlifeexpectancies/bulletins/healthstatelifeexpectanciesuk/between2011to2013and2020to2022#:~:text=Healthy%20life%20expectancy%20(HLE)%20at,%2C%2060.3%20years%20for%20females). This implies that, *on average, the last 20.6% of men's life are spent with poor and failing health.* By contrast, for my father, HLE and LE were almost identical.

When I worked as a what most of the UK calls a health economist, the official name of my role was 'operational researcher'. At my employer, the term 'health economist' was reserved for a different sort of role, focused on accurately and consistently estimating quality of life, and the effects that various diseases and conditions can have on it. This type of health economist often run experiments, including what's known as 'discrete choice experiments' (DCE). DCE are really another name for asking a barrage of 'would you rather?' questions, and a framework for interpreting the responses in a consistent way. Here's an example:

> Would you rather:

> (A) Live for 100% of average life expectancy, spending the last 20% of your life in poor health? 

> (B) Live for 97% of average life expectancy, spending the last 0.2% of your life in poor health? 

This choice wasn't something my father was explicitly offered. But fate selected Option B for him. Maybe this is a latent coping mechanism speaking, but if I had to make this choice I would prefer Option B to Option A. The greatly increased amount of life lived in good health seems to more than adequately compensate for the slight decrement in overall longevity. The 'indifference curve' - the point at which people can't easily decide between the two options - would likely only be found if the 97% in Option B were tuned down to a value, perhaps, in the high 80% to low 90% range. As Hobson's Choices go, the Option B that was selected for my father seems much better than the statistical average of Option A. 

More poetically, I like the term **'shadow life'** to refer to the gap between LE and HLE. These are the years in which the functional horizon of one's existence slowly dwindle, from thousands and hundreds of miles (more than comfortable going on international flights and travelling, including driving, for six or more hours), to tens of miles, then eventually to just single inches (i.e. being bedbound and unable to walk).[^2] My father experienced no shadow life, and for that I'm extremely grateful. 

[^2]: I remember a talk by, I think, a nursing lecturer, on the types of question that work best for estimating how frail people are, given their responses in the affirmative or negative to questions on whether they can do X, Y and Z unaided. Apparently the item on whether a person can cut their own toenails is quite a strong indicator of frailty overall. If you can't cut your toenails unaided you may already be living a shadow life.

There's another, related term I've been thinking about a lot in recent days: **'living death'**. Living death is what I refer to when, especially due to 'heroic' medical intervention, someone who would otherwise have died definitively due to a condition or incident, instead is 'rescued' from death, only to be stuck, suspended, in a durable but precarious state between life and death, in which the quality of life really is or can be negative ('WTD'), and the only real prognosis is towards further tortuous and torturious progression towards death itself. Often, living death is more than just a metaphor: the death of parts of a brain due to oxygen starvation in the case of a stroke, for example; and the death (necrosis) of parts of a body in the case of advanced diabetes (often resulting in amputation of dead flesh from a body otherwise trying to stay alive); and the starving out of healthy parts of the body to feed the rampant growth of metastasising tumours in the case of cancers. 

When I was first told my father had experienced a heart attack, one of my first questions was to clarify it wasn't a stroke. 'Surviving' a stroke can leave the 'survivor' in a state of living death. [The modified Rankin scale (MRS)](https://www.mdcalc.com/calc/1890/modified-rankin-scale-neurologic-disability) is a common measure for describing different severities of outcome following a stroke, and is reproduced below:

| Level | Description | DALY decrement | 
|-------|:------------|:---------------|
| 0     | No symptoms at all | 0.000 | 
| 1     | No significant disability despite symptoms; able to carry out all usual duties and activities | 0.046 |
| 2     | Slight disability; unable to carry out all previous activities, but able to look after own affairs without assistance| 0.212 | 
| 3     | Moderate disability; requiring some help, but able to walk without assistance | 0.331 |
| 4     | Moderately severe disability; unable to walk and attend to bodily needs without assistance | 0.652 | 
| 5     | Severe disability; bedridden, incontinent and requiring constant nursing care and attention | 0.944 | 
| 6     | Dead | 1.000 | 

The values in the last column are disability weights reported in [this paper](https://pmc.ncbi.nlm.nih.gov/articles/PMC2788070/), with values of 1 indicating no quality of life, and 0 indicating no decrement in quality of life. The mRS describes, in medical terms, a secular analogue of the concentric circles of Hell, with levels 4 and 5 (especially) describing the infliction of a type of existence that only a sadist or a psychopath would wish to inflict on even the worst in society. If a populist politician proposed intentionally disabling rapists and murderers to the levels described in levels 4 or 5 of the mRS, they would quite rightly be condemned as more evil and dangerous than Nazis and fascists. But all too often, when someone is admitted to a hospital with a severe stroke, out of instinct friends and family tend to hope for any outcome other than mRS level 6. 

I didn't. When I heard that my father was having a stroke my hope was for *any outcome other than mRS levels 4 and 5*. I've known two people who have been rendered at these disablement levels: a grandfather, previously a very successful entrepreneur, who was left in this state for months on end; and a retired GP, with an insatiable curiosity and enthusiasm for learning new things, who ran a discussion and non fiction book group I was part of in Glasgow, who spent over a year in this state. I don't believe anyone really acting and thinking with considered compassion would hope for a loved one to be left to suffer in this state. It's not a final chapter I would ever be cruel enough to wish for the father I loved. 

And that's why, when I heard, slightly before midnight, that the series of events that started after 6pm had killed my father outright, rather than left him to suffer the kind of unconscionable living death for an indetermine period as described above, I was shocked, and I was sad. But I was also relieved.

The Book of Nigel, unlike the books of perhaps the majority of lives, did not include at or near the end a chapter titled 'shadow life', detailing slow and progressive decline. And unlike a sizeable and unfortunate minority of people, did not end with a short but brutal 'living death' chapter in which the hero of the story is imprisoned in their own body, then tortured without mercy until they expire. 

No. The Book of Nigel was *almost* of standard length, but unlike most standard length books contained almost no bad chapters. My father's life ended, but unlike most lives of its duration, included almost no shadow life or living death. My father was healthy, active, happy, enjoying life. And then, about a week later, he wasn't. 

## Life is short

Sometimes things I find profound are also profane, or incidental, or even bathetic. One thing that's stuck with me for decades is [an advert from the 1990s](https://youtu.be/ELPRVu0GxYo?si=2mUxCwgSQ2CbwchI). As I remember it:[^3] a mother is giving birth in a hospital, screaming. With a forceful, painful push her infant is ejected from her womb, and starts flying in an upwards parabola, screaming. The infant smashes through the hospital window and ages into a boy, still screaming. Then as he continues to shoot through the air he becomes a young man, then starts to descend and becomes middle aged, then old, and then frail. All the while, screaming. As he heads back to the ground, his skin wrinkles and his teeth fall out, and he's still screaming. Finally, he crashes into a freshly dug grave, and only then falls silent. In the silence the following text appears: *"Life is short. Play more."*

[^3]: This description was written before reviewing the advert as shown in the link, then not modified afterwards. I seem to have remembered most of the details, except in the advert the screaming only starts after childhood; and I had presumed that the text appears over the final image of the grave, when instead it appears after first fading to black. 

The advert received many complaints. Many found it offensive. It may even have been pulled off television prematurely. But to me, in five words, it expresses a premise and conclusion I wholeheartedly believe in. Of course, there are people who might disagree with the premise: compared with cats and dogs, we do live a long time. And there might also be people who agree with the premise but draw the opposite conclusion: "Life is short. Play less." And although this is of course subjective such people are categorically wrong. A Calvinist hangover at best; a pathological compulsion to starve joy from a finite existence at worst. Play *more*, not less. 

My father was fortunate to have worked hard, then retired early, taking advantage of a 'manpower reduction' initiative to start receiving his pension at the age of 60 rather than 65. He spent over sixteen years keeping busy with generous and productive play: volunteering for a charity that promoted the social virtues of music and art; volunteering for another charity focused on promoting happiness and the good life; offering mentorship to those at earlier life stages to help them live more fulfilling and happier lives; planning at-least-annual holidays with both his wife and broader family at home and abroad, including to New Zealand and Australia, places that he loved visiting; running a small business, and taking up a trustee role at a pension fund; planning and executing all manner of home improvement, including major renovation of his own property, as well as the supporting the purchase and development of a house I lived in as a student; playing golf regularly and developing close-knit bonds with other other seniors at a nearby club. 

## The Books of Nigel

But the most consistent source of play my father engaged in was through the worlds he invited into his head. A science fiction enthusiast from a young age, my father was hyperlexic and voracious in his consumption of doorstop-sized space operas, swashbucklers, fantasies, narrativised thought experiments and allegories. He was around 200 pages into 800 page science fiction book when he died; the challenge of finishing the book he started was given to our oldest cousin, whose own extensive book collection was dwarfed by my father's. A few years ago, as part of a home extension, my father acquired wood flooring in the attic, allowing the top of the house to finally become his personal library, with his collection on private display on shelves, instead of buried in storage boxes. For the most part, the collection remained largely contained in the attic, but a wall of bookcases one side of the exercise equipment proudly displays many of his hardbacks, and on the other side of the same room sits a largely complete collection of a British sci-fi short story magazine that was most active in those post-war decades of techno-optimism, when sci-fi was more preoccupied with utopia and expanding frontiers than, as perhaps after the oil crises of the mid 1970s, with dystopia and collapsing societies. 

In those with playful minds like my father, the possibly millions of pages of stories that my father acquired throughout his lifetime could live again. The worlds that my father visited decades ago, the epic stories he experienced through his inhaled streams of black-on-white text, are those that potentially hundreds of other likeminded folk could become lost in for many thousands of hours. I would love to see this aspect of my father's life, alone, having an afterlife, a legacy of influence, a way of changing and becoming part of other's lives and minds, that could itself continue to impact on others for potentially decades longer. *A book is a seed and the mind is its soil.* Through The Books of Nigel, my father can continue to enrich the lives of others he never met, much as he greatly enriched the lives of those who knew and loved him directly. 

Though I think my father might have found The Book of Mormon unnecessarily crude (because it is), its implicit but insistent claim that stories - even and especially fantastical and fanciful stories - are vital to living and living well, is something that he spent his lifetime agreeing with. He didn't get the chance to see the show, but he already knew the gist of it without realising.


**Nigel William Minton, 1948-2024.** *May he continue to live long and happily in our thoughts.* 
